In [60]:
import pandas as pd

In [61]:
df1 = pd.read_csv("../../../Collected Data/Octoparse_AllBusinesses/Dammam Coffee shops.csv")
df2 = pd.read_csv("../../../Collected Data/Octoparse_AllBusinesses/Dhahran Coffee shops.csv")
df3 = pd.read_csv("../../../Collected Data/Octoparse_AllBusinesses/Khobar Coffee shops.csv")
df = pd.concat([df1, df2, df3], ignore_index=True)

In [62]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743 entries, 0 to 742
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   keyword                  743 non-null    object
 1   Title                    743 non-null    object
 2   Review_Count             699 non-null    float64
 3   Rating                   699 non-null    float64
 4   Address                  743 non-null    object
 5   Country                  743 non-null    object
 6   City                     743 non-null    object
 7   State                    0 non-null      float64
 8   Website                  412 non-null    object
 9   Phone                    453 non-null    object
 10  Open_Time                743 non-null    object
 11  Page_URL                 743 non-null    object
 12  Google_id                743 non-null    object
 13  Place_id                 743 non-null    object
 14  Additional_info          17 non-null     object
 15  Latitude                 743 non-null    float64
 16  Longitude                743 non-null    float64
 17  Category                 743 non-null    object
 18  Main_image               682 non-null    object
 19  Image_1                  677 non-null    object
 20  Image_2                  649 non-null    object
 21  Image_3                  586 non-null    object
 22  Description              48 non-null     object
 23  Price_Range              488 non-null    object
 24  Current_Status           55 non-null     object
 25  Plus_code_URL            607 non-null    object
 26  Plus_code                607 non-null    object
 27  Delivery                 670 non-null    object
 28  Open_Time_Monday         589 non-null    object
 29  Open_Time_Tuesday        589 non-null    object
 30  Open_Time_Wednesday      589 non-null    object
 31  Open_Time_Thursday       589 non-null    object
 32  Open_Time_Friday         589 non-null    object
 33  Open_Time_Saturday       589 non-null    object
 34  Open_Time_Sunday         589 non-null    object
 35  Popular_times_Monday     411 non-null    object
 36  Popular_times_Tuesday    411 non-null    object
 37  Popular_times_Wednesday  411 non-null    object
 38  Popular_times_Thursday   411 non-null    object
 39  Popular_times_Friday     411 non-null    object
 40  Popular_times_Saturday   411 non-null    object
 41  Popular_times_Sunday     411 non-null    object
dtypes: float64(5), object(37)
memory usage: 243.9+ KB

,keyword,Title,Review_Count,Rating,Address,Country,City,State,Website,Phone,Open_Time,Page_URL,Google_id,Place_id,Additional_info,Latitude,Longitude,Category,Main_image,Image_1,Image_2,Image_3,Description,Price_Range,Current_Status,Plus_code_URL,Plus_code,Delivery,Open_Time_Monday,Open_Time_Tuesday,Open_Time_Wednesday,Open_Time_Thursday,Open_Time_Friday,Open_Time_Saturday,Open_Time_Sunday,Popular_times_Monday,Popular_times_Tuesday,Popular_times_Wednesday,Popular_times_Thursday,Popular_times_Friday,Popular_times_Saturday,Popular_times_Sunday
0,Coffee shop,مقهى بساطة coffee Basata,169.0,4.8,"شارع خادم الحرمين - الظهران, Al Khobar 31952, ...",SA,Al Khobar,NaN,https://linktr.ee/basatacafe.sa,+966 51 060 1227,Identifies as women-ownedSunday Open 24 hours ...,https://www.google.com/maps/place/مقهى+بساطة+c...,0x3e49e99c0ed45945:0xb5c1f6f04d1b52e5,ChIJRVnUDpzpST4R5VIbTfD2wbU,Identifies as women-owned,26.284723,50.196039,coffee shops,https://lh5.googleusercontent.com/p/AF1QipMTMp...,https://lh5.googleusercontent.com/p/AF1QipPW_N...,https://lh5.googleusercontent.com/p/AF1QipMcKl...,https://lh5.googleusercontent.com/p/AF1QipOozz...,NaN,NaN,NaN,https://plus.codes/75MW+VC Al Khobar Saudi Arabia,75MW+VC Al Khobar Saudi Arabia,NaN,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-03-30,36% busy at 4 AM;55% busy at 5 AM;68% busy at ...,50% busy at 4 AM;47% busy at 5 AM;42% busy at ...,34% busy at 4 AM;34% busy at 5 AM;34% busy at ...,55% busy at 4 AM;28% busy at 5 AM;26% busy at ...,36% busy at 4 AM;26% busy at 5 AM;31% busy at ...,36% busy at 4 AM;39% busy at 5 AM;36% busy at ...,57% busy at 4 AM;55% busy at 5 AM;63% busy at ...
1,Coffee shop,Weeks coffee,15.0,4.8,"C4W2+2RP, Al Souq, Dammam 32416, Saudi Arabia",SA,Dammam,NaN,NaN,NaN,,https://www.google.com/maps/place/Weeks+coffee...,0x3e49fb224fbf4255:0xc4947d58a69ef687,ChIJVUK_TyL7ST4Rh_aeplh9lMQ,NaN,26.445087,50.102090,coffee shops,https://lh5.googleusercontent.com/p/AF1QipOmzj...,https://lh5.googleusercontent.com/p/AF1QipOmzj...,https://lh5.googleusercontent.com/p/AF1QipPvsA...,https://lh5.googleusercontent.com/p/AF1QipNnrO...,NaN,SAR 1–20,NaN,NaN,NaN,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Coffee shop,Remedy Roasters & Specialty Coffee | ريمدي محم...,1194.0,4.9,"King Abdullah Bin Abdulaziz Road, Ash Shati As...",SA,Dammam,NaN,http://remedy.sa/,NaN,Saturday 7:30 PM–4:30 AM 2025-03-29\r\nSunday...,https://www.google.com/maps/place/Remedy+Roast...,0x3e49fb6b24131577:0x26026498f8fae40b,ChIJdxUTJGv7ST4RC-T6-JhkAiY,NaN,26.479433,50.132684,Coffee roasters,https://lh5.googleusercontent.com/p/AF1QipMMUv...,https://lh5.googleusercontent.com/p/AF1QipP6gh...,https://lh5.googleusercontent.com/p/AF1QipPD-6...,https://lh5.googleusercontent.com/p/AF1QipO45v...,NaN,SAR 20–40,NaN,https://plus.codes/F4HM+Q3 Dammam Saudi Arabia,F4HM+Q3 Dammam Saudi Arabia,Takeout,Monday 7:30 PM–4:30 AM 2025-03-31,Tuesday 7:30 PM–4:30 AM 2025-04-01,Wednesday 7:30 PM–4:30 AM 2025-04-02,Thursday 7:30 PM–4:30 AM 2025-04-03,Friday 7:30 PM–4:30 AM 2025-04-04,Saturday 7:30 PM–4:30 AM 2025-03-29,Sunday 7:30 PM–4:30 AM 2025-03-30,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...
3,Coffee shop,Coffee house,7.0,4.4,"EDJD8547، 8547 السادس عشر، 3741، حي السوق،, Da...",SA,Dammam,NaN,NaN,NaN,,https://www.google.com/maps/place/Coffee+house...,0x3e49fd61415f7df9:0xbfa51157adfd4c02,ChIJ-X1fQWH9ST4RAkz9rVcRpb8,NaN,26.442100,50.099043,coffee shops,https://lh5.googleusercontent.com/p/AF1QipN7Xd...,https://lh5.googleusercontent.com/p/AF1QipN7Xd...,NaN,NaN,NaN,NaN,NaN,https://plus.codes/C3RX+RJ Dammam Saudi Arabia,C3RX+RJ Dammam Saudi Arabia,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Coffee shop,TCG - The Coffee Group,23.0,5.0,"8070 King Khalid Rd, Sinayiat Al Thuqba, 2678,...",SA,Al Khobar,NaN,https://www.instagram.com/tcg.academy?igsh=MWF...,NaN,,https://www.google.com/maps/place/TCG+-+The+Co...,0x3e49c349b4281f1b:0xb2f679c5d2e7109,ChIJGx8otEnDST4RCXEuXZxnLws,NaN,26.250624,50.198796,coffee shops,https://lh5.googleusercontent.com/p/AF1QipOTDe...,https://lh5.googleusercontent.com/p/AF1QipMN86...,NaN,NaN,NaN,NaN,NaN,https://plus.codes/752X+6G Al Khobar Saudi Arabia,752X+6G Al Khobar Saudi Arabia,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
#Check business status counts ??? we don't have it 
#status_counts_df = df['Business Status'].value_counts().reset_index()
#status_counts_df.columns = ['Business Status', 'Count']
#print(status_counts_df)

In [64]:
# Check for duplicates in the 'Google_id column'
duplicates = df[df.duplicated(subset=['Google_id'], keep=False)]

# Display duplicates
duplicates

,keyword,Title,Review_Count,Rating,Address,Country,City,State,Website,Phone,Open_Time,Page_URL,Google_id,Place_id,Additional_info,Latitude,Longitude,Category,Main_image,Image_1,Image_2,Image_3,Description,Price_Range,Current_Status,Plus_code_URL,Plus_code,Delivery,Open_Time_Monday,Open_Time_Tuesday,Open_Time_Wednesday,Open_Time_Thursday,Open_Time_Friday,Open_Time_Saturday,Open_Time_Sunday,Popular_times_Monday,Popular_times_Tuesday,Popular_times_Wednesday,Popular_times_Thursday,Popular_times_Friday,Popular_times_Saturday,Popular_times_Sunday
0,Coffee shop,مقهى بساطة coffee Basata,169.0,4.8,"شارع خادم الحرمين - الظهران, Al Khobar 31952, ...",SA,Al Khobar,NaN,https://linktr.ee/basatacafe.sa,+966 51 060 1227,Identifies as women-ownedSunday Open 24 hours ...,https://www.google.com/maps/place/مقهى+بساطة+c...,0x3e49e99c0ed45945:0xb5c1f6f04d1b52e5,ChIJRVnUDpzpST4R5VIbTfD2wbU,Identifies as women-owned,26.284723,50.196039,coffee shops,https://lh5.googleusercontent.com/p/AF1QipMTMp...,https://lh5.googleusercontent.com/p/AF1QipPW_N...,https://lh5.googleusercontent.com/p/AF1QipMcKl...,https://lh5.googleusercontent.com/p/AF1QipOozz...,NaN,NaN,NaN,https://plus.codes/75MW+VC Al Khobar Saudi Arabia,75MW+VC Al Khobar Saudi Arabia,NaN,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-03-30,36% busy at 4 AM;55% busy at 5 AM;68% busy at ...,50% busy at 4 AM;47% busy at 5 AM;42% busy at ...,34% busy at 4 AM;34% busy at 5 AM;34% busy at ...,55% busy at 4 AM;28% busy at 5 AM;26% busy at ...,36% busy at 4 AM;26% busy at 5 AM;31% busy at ...,36% busy at 4 AM;39% busy at 5 AM;36% busy at ...,57% busy at 4 AM;55% busy at 5 AM;63% busy at ...
2,Coffee shop,Remedy Roasters & Specialty Coffee | ريمدي محم...,1194.0,4.9,"King Abdullah Bin Abdulaziz Road, Ash Shati As...",SA,Dammam,NaN,http://remedy.sa/,NaN,Saturday 7:30 PM–4:30 AM 2025-03-29\r\nSunday...,https://www.google.com/maps/place/Remedy+Roast...,0x3e49fb6b24131577:0x26026498f8fae40b,ChIJdxUTJGv7ST4RC-T6-JhkAiY,NaN,26.479433,50.132684,Coffee roasters,https://lh5.googleusercontent.com/p/AF1QipMMUv...,https://lh5.googleusercontent.com/p/AF1QipP6gh...,https://lh5.googleusercontent.com/p/AF1QipPD-6...,https://lh5.googleusercontent.com/p/AF1QipO45v...,NaN,SAR 20–40,NaN,https://plus.codes/F4HM+Q3 Dammam Saudi Arabia,F4HM+Q3 Dammam Saudi Arabia,Takeout,Monday 7:30 PM–4:30 AM 2025-03-31,Tuesday 7:30 PM–4:30 AM 2025-04-01,Wednesday 7:30 PM–4:30 AM 2025-04-02,Thursday 7:30 PM–4:30 AM 2025-04-03,Friday 7:30 PM–4:30 AM 2025-04-04,Saturday 7:30 PM–4:30 AM 2025-03-29,Sunday 7:30 PM–4:30 AM 2025-03-30,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...
6,Coffee shop,Mana,46.0,4.5,"As Safa, Unit no. 20, 8021 king saud road, Dam...",SA,Dammam,NaN,https://www.instagram.com/manacafe_sa/,+966 13 803 7852,Sunday Open 24 hours 2025-03-30\r\nMonday Ope...,https://www.google.com/maps/place/Mana/data=!4...,0x3e49e544e0d1429b:0x8aa339bfacaac4bd,ChIJm0LR4ETlST4RvcSqrL85o4o,NaN,26.388974,50.178380,coffee shops,https://lh5.googleusercontent.com/p/AF1QipPXDK...,https://lh5.googleusercontent.com/p/AF1QipNvQ2...,https://lh5.googleusercontent.com/p/AF1QipMSPV...,NaN,NaN,NaN,NaN,https://plus.codes/95QH+H9 Dammam Saudi Arabia,95QH+H9 Dammam Saudi Arabia,Delivery,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-03-30,28% busy at 4 AM;28% busy at 5 AM;48% busy at ...,53% busy at 4 AM;53% busy at 5 AM;62% busy at ...,31% busy at 4 AM;37% busy at 5 AM;42% busy at ...,37% busy at 4 AM;48% busy at 5 AM;60% busy at ...,42% busy at 4 AM;55% busy at 5 AM;53% busy at ...,46% busy at 4 AM;37% busy at 5 AM;48% busy at ...,35% busy at 4 AM;42% busy at 5 AM;57% busy at ...
7,Coffee shop,ديڤا كافيه -Diva coffee,48.0,4.7,"94PC+MP, Al Basatin, Dammam 32235, Saudi Arabia",SA,Dammam,NaN,NaN,NaN,,https://www.google.com/maps/place/ديڤا+كافيه+-...,0x3e49e5000c8dc433:0x76d1f62d9a59698f,ChIJM8SNDADlST4Rj2lZmi320XY,NaN,26.386050,50.122164,coffee shops,https://lh5.googleusercontent.com/p/AF1QipPf9d...,https://lh5.googleusercontent.com/p/AF1QipOT1r...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIABIhADyd...,NaN,SAR 1–20,NaN,NaN,NaN,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Coffee shop,Chemistry Coffee كيمستري كوفي,1384.0,4.1,"Alimam Muhammad Ibn Abd Al Wahab, Dammam 32271...",SA,Dammam,NaN,http://www.chemistrycoffeesa.com/,NaN,Sunday Open 24 hours 2025-03-30\r\nMonday Ope...,https://www.google.com/maps/place/Chemistry+Co...,0x3e49e36613befa59:0xcf84b23b06a2cc52,ChIJWfq-E2bjST4RUsyiBjuyhM8,NaN,26.345880,50.046341,coffee shops,https://lh5.googleusercontent.com/p/AF1QipOq3h...,https://lh5.googleusercontent.com/p/AF1QipOLhT...,https://lh5.googleusercontent.com/p/AF1QipNePM...,https://lh5.googleusercontent.com/p/AF1QipPaaW...,NaN,SAR 20–40,NaN,https://plus.codes/82WW+9G Dammam Saudi Arabia,82WW+9G Dammam Saudi Arabia,Curbside pickup,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-03-30,11% busy at 4 AM;13% busy at 5 AM;16% busy at ...,13% busy at 4 AM;12% busy at 5 AM;16% busy at ...,15% busy at 4 AM;18% busy at 5 AM;23% busy at ...,14% busy at 4 AM;15% busy at 5 AM;18% busy at ...,6% busy at 4 AM;6% busy at 5 AM;7% busy at 6 A...,16% busy at 4 AM;18% busy at 5 AM;20% busy at ...,10% busy at 4 AM;10% busy at 5 AM;15% busy at ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,Coffee shop,ايت اوز-8Oz Coffee,318.0,4.1,"ECJA6652 ربيعة بن السكن، 3894, Al Sheraa, Al K...",SA,Al Khobar,NaN,NaN,NaN,Monday Open 24 hours 2025-03-31\r\nTuesday Op...,https://www.google.com/maps/place/ايت+اوز-8Oz+...,0x3e49db3b81912777:0x79afe5949ab95644,ChIJdyeRgTvbST4RRFa5mpTlr3k,NaN,26.152098,50.161310,coffee shops,https://lh3.googleusercontent.com/gps-cs-s/AB5...,https://lh5.googleusercontent.com/p/AF1QipORBn...,https://lh5.googleusercontent.com/p/AF1QipNwy-...,https://lh5.googleusercontent.com/p/AF1QipPF43...,NaN,NaN,NaN,https://plus.codes/5526+RG Al Khobar Saudi Arabia,5526+RG Al Khobar Saudi Arabia,No-contact delivery,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-04-06,6% busy at 4 AM;10% busy at 5 AM;19% busy at 6...,12% busy at 4 AM;8% busy at 5 AM;8% busy at 6 ...,19% busy at 4 AM;10% busy at 5 AM;6% busy at 6...,17% busy at 4 AM;12% busy at 5 AM;4% busy at 6...,12% busy at 4 AM;10% busy at 5 AM;14% busy at ...,10% busy at 4 AM;8% busy at 5 AM;8% busy at 6 ...,10% busy at 4 AM;17% busy at 5 AM;23% busy at ...
728,Coffee shop,مقهى كريبريستا,14.0,4.3,"55M7+MV9, Al Sawari, Al Khobar 34724, Saudi Ar...",SA,Al Khobar,NaN,NaN,NaN,,https://www.google.com/maps/place/مقهى+كريبريس...,0x3e49dd9d892270a5:0x13e66dff67f868ca,ChIJpXAiiZ3dST4Rymj4Z_9t5hM,NaN,26.184172,50.164730,coffee shops,https://lh5.googleusercontent.com/p/AF1QipOfvw...,https://lh5.googleusercontent.com/p/AF1QipNSc1...,https://lh5.googleusercontent.com/p/AF1QipOd6o...,NaN,NaN,NaN,Temporarily closed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,Coffee shop,ارت سويت الشراع,255.0,4.3,"الحسين الوسطي, Al Sheraa, Al Khobar 34741, Sau...",SA,Al Khobar,NaN,https://linktr.ee/art_sweet,+966 53 261 6663,Monday 2:30 PM–2 AM 2025-03-31\r\nTuesday 2:3...,https://www.google.com/maps/place/ارت+سويت+الش...,0x3e49dd8cdcb6239b:0xcf9d45fd9c78d9eb,ChIJmyO23IzdST4R69l4nP1Fnc8,NaN,26.174051,50.152580,attractions,https://lh5.googleusercontent.com/p/AF1QipPjvr...,https://lh5.googleusercontent.com/p/AF1QipOXC_...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,NaN,NaN,https://plus.codes/55F3+J2 Al Khobar Saudi Arabia,55F3+J2 Al Khobar Saudi Arabia,Delivery,Monday 2:30 PM–2 AM 2025-03-31,Tuesday 2:30 PM–2 AM 2025-04-01,Wednesday 2:30 PM–2 AM 2025-04-02,Thursday 2:30 PM–2 AM 2025-04-03,Friday 2:30 PM–2 AM 2025-04-04,Saturday 2:30 PM–2 AM 2025-04-05,Sunday 2:30 PM–2 AM 2025-04-06,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...
732,Coffee shop,مؤسسة أوقات شرق التجارية,18.0,4.7,"Al Sawari, Al Khobar 34724, Saudi Arabia",SA,Al Khobar,NaN,NaN,NaN,,https://www.google.com/maps/place/مؤسسة+أوقات+...,0x3e49ddf619e585ad:0xa5e44e8342e2c84b,ChIJrYXlGfbdST4RS8jiQoNO5KU,NaN,26.187601,50.160091,coffee shops,https://lh3.googleusercontent.com/gps-cs-s/AB5...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 20–40,NaN,https://plus.codes/55Q6+22 Al Khobar Saudi Arabia,55Q6+22 Al Khobar Saudi Arabia,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
741,Coffee shop,فلافي كيك وقهوة (وايتي كيك Whitey fluffy),108.0,4.9,"شارع الدارقطني, Al Amwaj, Al Khobar 34742, Sau...",SA,Al Khobar,NaN,https://www.instagram.com/whity_fluffy/profile...,+966 50 022 1781,Monday 10 AM–2 AM 2025-03-31\r\nTuesday 10 AM...,https://www.google.com/maps/place/فلافي+كيك+وق...,0x3e49db006e16ffab:0x2f310ce60eaec0ed,ChIJq_8WbgDbST4R7cCuDuYMMS8,NaN,26.153545,50.144478,متجر القهوة,https://lh3.googleusercontent.com/gps-cs-s/AB5...,https://lh5.googleusercontent.com/p/AF1QipP9Qq...,https://lh5.googleusercontent.com/p/AF1QipO7Vc...,https://lh5.googleusercontent.com/p/AF1QipPbCV...,NaN,SAR 20–40,NaN,https://plus.codes/543V+CQ Al Khobar Saudi Arabia,543V+CQ Al Khobar Saudi Arabia,Delivery,Monday 10 AM–2 AM 2025-03-31,Tuesday 10 AM–2 AM 2025-04-01,Wednesday 10 AM–2 AM 2025-04-02,Thursday 10 AM–2 AM 2025-04-03,Friday 1 PM–2 AM 2025-04-04,Saturday 10 AM–2 AM 2025-04-05,Sunday 10 AM–2 AM 2025-04-06,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...

In [65]:
# drop all occurunces except the first one
df = df.drop_duplicates(subset=['Google_id'], keep="first")
df.count()

keyword                    576
Title                      576
Review_Count               535
Rating                     535
Address                    576
Country                    576
City                       576
State                        0
Website                    300
Phone                      342
Open_Time                  576
Page_URL                   576
Google_id                  576
Place_id                   576
Additional_info             11
Latitude                   576
Longitude                  576
Category                   576
Main_image                 521
Image_1                    517
Image_2                    491
Image_3                    439
Description                 43
Price_Range                356
Current_Status              46
Plus_code_URL              462
Plus_code                  462
Delivery                   519
Open_Time_Monday           438
Open_Time_Tuesday          438
Open_Time_Wednesday        438
Open_Time_Thursday         438
Open_Time_Friday           438
Open_Time_Saturday         438
Open_Time_Sunday           438
Popular_times_Monday       306
Popular_times_Tuesday      306
Popular_times_Wednesday    306
Popular_times_Thursday     306
Popular_times_Friday       306
Popular_times_Saturday     306
Popular_times_Sunday       306
dtype: int64

In [66]:
pip install folium geopy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: folium in c:\users\farah\appdata\roaming\python\python312\site-packages (0.19.4)
Requirement already satisfied: geopy in c:\users\farah\appdata\roaming\python\python312\site-packages (2.4.1)
Requirement already satisfied: pandas in c:\users\farah\appdata\roaming\python\python312\site-packages (2.1.2)
Requirement already satisfied: branca>=0.6.0 in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (1.26.1)
Requirement already satisfied: requests in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (2025.1.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\farah\appdata\roaming\python\python312\site-packages (from geopy) (2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\farah\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\farah\appdata\roaming\python\python312\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\farah\appdata\roaming\python\python312\site-packages (from pandas) (2023.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\farah\appdata\roaming\python\python312\site-packages (from jinja2>=2.9->folium) (2.1.5)
Requirement already satisfied: six>=1.5 in c:\users\farah\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [35]:
#df.insert(0, 'ID', range(0, 0 + len(df)))
#df

In [67]:
import folium
import pandas as pd
from geopy.distance import geodesic


# Create a Folium Map Centered at First Location
m = folium.Map(location=[df["Latitude"].mean(), df["Longitude"].mean()], zoom_start=16)

# Add Markers to Map
for index, row in df.iterrows():
    folium.Marker(
        location=[row["Latitude"], row["Longitude"]],
        popup=[row["Title"], row["Place_id"]],
        icon=folium.Icon(color="blue")  # Mark possible duplicates
    ).add_to(m)

# Save and Display Map
m.save("map.html")
m

In [68]:
# deleting POIs Not in Dammam, Khobar, Dhahran: 
df = df[~df["City"].isin(["Al Qatif", "Qatif", "Saihat", "Anak"])]

# deleting POIs out of the scope (Playground, Fuel Station, etc): 
df = df[~df["Place_id"].isin(['ChIJN3tmwvflST4RQfR6Ocvo8qM', 'ChIJpcQsSwDhST4R8IbiWp3--A4', 'ChIJqzPbiT39ST4RyUnotC6_vOs','ChIJVw0sMwADNj4RYLGEF6WMsBw', 'ChIJBzaWbw4PNj4R0Wx7UIbbKTQ', 'ChIJcb7yukojNj4Rm7UcPXmo7hQ', 'ChIJe6T3XwAfNj4Rryj_aEkShKs', 'ChIJ-X-Kxo7bST4RNVjbCEKackE', 'ChIJ-YvJf17vST4RUznnprkzFdI', 'ChIJjW_1FwDfST4RL6hQH1CkoMQ','ChIJLyuReAADNj4R5v7cPcGD_5E', 'ChIJh4r3PwDfST4RcmQBG-AO2XM', 'ChIJz8OgbwDfST4RpRUSxNUGIck', 'ChIJ020pTADfST4RL3Jd1Ji1TiI'])]

In [69]:
df.count()

keyword                    552
Title                      552
Review_Count               513
Rating                     513
Address                    552
Country                    552
City                       552
State                        0
Website                    288
Phone                      330
Open_Time                  552
Page_URL                   552
Google_id                  552
Place_id                   552
Additional_info             11
Latitude                   552
Longitude                  552
Category                   552
Main_image                 499
Image_1                    495
Image_2                    470
Image_3                    420
Description                 43
Price_Range                342
Current_Status              45
Plus_code_URL              443
Plus_code                  443
Delivery                   499
Open_Time_Monday           422
Open_Time_Tuesday          422
Open_Time_Wednesday        422
Open_Time_Thursday         422
Open_Time_Friday           422
Open_Time_Saturday         422
Open_Time_Sunday           422
Popular_times_Monday       293
Popular_times_Tuesday      293
Popular_times_Wednesday    293
Popular_times_Thursday     293
Popular_times_Friday       293
Popular_times_Saturday     293
Popular_times_Sunday       293
dtype: int64

In [71]:
print(df.to_string())

         keyword                                                                      Title  Review_Count  Rating                                                                                                                                        Address Country        City  State                                                                                                                                                                                                    Website                       Phone                                                                                                                                                                                                                                                                                                                                                                Open_Time                                                                                                                                                                                                                Page_URL                              Google_id                     Place_id            Additional_info   Latitude  Longitude            Category                                                                                                                                                                                                                                                 Main_image                                                                                                                   Image_1                                                                                                                   Image_2                                                                                             Image_3                                                                                           Description Price_Range      Current_Status                                      Plus_code_URL                       Plus_code                           Delivery                                Open_Time_Monday                                Open_Time_Tuesday                                Open_Time_Wednesday                                Open_Time_Thursday                                 Open_Time_Friday                                Open_Time_Saturday                                Open_Time_Sunday                                                                                                                                                                                                                                                                                                                                                                                                                Popular_times_Monday                                                                                                                                                                                                                                                                                                                                                                                                             Popular_times_Tuesday                                                                                                                                                                                                                                                                                                                                                                                                           Popular_times_Wednesday                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Popular_times_Thursday                                                                                                                                                                                                                                                                                                                                                                                                              Popular_times_Friday                                                                                                                                                                                                                                                                                                                                                                                                            Popular_times_Saturday                                                                                                                                                                                                                                                                                                                                                                                                                                                             Popular_times_Sunday
0    Coffee shop                                                   مقهى بساطة coffee Basata         169.0     4.8                                                                                     شارع خادم الحرمين - الظهران, Al Khobar 31952, Saudi Arabia      SA   Al Khobar    NaN                                                                                                                                                                            https://linktr.ee/basatacafe.sa            +966 51 060 1227                                                                           Identifies as women-ownedSunday Open 24 hours  2025-03-30\r\nMonday Open 24 hours  2025-03-31\r\nTuesday Open 24 hours  2025-04-01\r\nWednesday Open 24 hours  2025-04-02\r\nThursday Open 24 hours  2025-04-03\r\nFriday Open 24 hours  2025-04-04\r\nSaturday Open 24 hours  2025-04-05\r\n                                                   https://www.google.com/maps/place/مقهى+بساطة+coffee+Basata/data=!4m5!3m4!1s0x3e49e99c0ed45945:0xb5c1f6f04d1b52e5!8m2!3d26.2847233!4d50.1960392?authuser=0&hl=en&rclk=1  0x3e49e99c0ed45945:0xb5c1f6f04d1b52e5  ChIJRVnUDpzpST4R5VIbTfD2wbU  Identifies as women-owned  26.284723  50.196039        coffee shops                                                                                                                                                            https://lh5.googleusercontent.com/p/AF1QipMTMpdPqiKiAfegSseaN4pyDTUaeyucZ_S3ev6J=w408-h306-k-no                        https://lh5.googleusercontent.com/p/AF1QipPW_NrpAG1Ucqg1XN9anFnnPSRKI4-HreTnf9VT=w1024-h960-p-k-no                        https://lh5.googleusercontent.com/p/AF1QipMcKlfc-q4O9U5l0cpaaX8KQijk9obO-HzrpBl1=w1024-h960-p-k-no  https://lh5.googleusercontent.com/p/AF1QipOozzvuCmZeFabBV4DKepigoYr338itQ1TKHpFx=w1024-h960-p-k-no                                                                                                   NaN         NaN                 NaN  https://plus.codes/75MW+VC Al Khobar Saudi Arabia  75MW+VC Al Khobar Saudi Arabia                                NaN                Monday Open 24 hours  2025-03-31                Tuesday Open 24 hours  2025-04-01                Wednesday Open 24 hours  2025-04-02                Thursday Open 24 hours  2025-04-03                 Friday Open 24 hours  2025-04-04                Saturday Open 24 hours  2025-04-05                Sunday Open 24 hours  2025-03-30      36% busy at 4 AM;55% busy at 5 AM;68% busy at 6 AM;84% busy at 7 AM;63% busy at 8 AM;55% busy at 9 AM;47% busy at 10 AM;42% busy at 11 AM;42% busy at 12 PM;28% busy at 1 PM;18% busy at 2 PM;18% busy at 3 PM;34% busy at 4 PM;57% busy at 5 PM;71% busy at 6 PM;55% busy at 7 PM;50% busy at 8 PM;42% busy at 9 PM;42% busy at 10 PM;42% busy at 11 PM;50% busy at 12 AM;63% busy at 1 AM;55% busy at 2 AM;47% busy at 3 AM;    50% busy at 4 AM;47% busy at 5 AM;42% busy at 6 AM;52% busy at 7 AM;50% busy at 8 AM;44% busy at 9 AM;31% busy at 10 AM;23% busy at 11 AM;31% busy at 12 PM;42% busy at 1 PM;55% busy at 2 PM;60% busy at 3 PM;60% busy at 4 PM;78% busy at 5 PM;78% busy at 6 PM;68% busy at 7 PM;71% busy at 8 PM;68% busy at 9 PM;68% busy at 10 PM;52% busy at 11 PM;50% busy at 12 AM;50% busy at 1 AM;44% busy at 2 AM;55% busy at 3 AM;   34% busy at 4 AM;34% busy at 5 AM;34% busy at 6 AM;55% busy at 7 AM;47% busy at 8 AM;60% busy at 9 AM;60% busy at 10 AM;71% busy at 11 AM;71% busy at 12 PM;65% busy at 1 PM;60% busy at 2 PM;52% busy at 3 PM;50% busy at 4 PM;52% busy at 5 PM;44% busy at 6 PM;44% busy at 7 PM;47% busy at 8 PM;52% busy at 9 PM;68% busy at 10 PM;73% busy at 11 PM;92% busy at 12 AM;100% busy at 1 AM;84% busy at 2 AM;57% busy at 3 AM;                                                                                                                                                                             55% busy at 4 AM;28% busy at 5 AM;26% busy at 6 AM;47% busy at 7 AM;65% busy at 8 AM;65% busy at 9 AM;60% busy at 10 AM;55% busy at 11 AM;50% busy at 12 PM;50% busy at 1 PM;52% busy at 2 PM;57% busy at 3 PM;52% busy at 4 PM;47% busy at 5 PM;71% busy at 6 PM;81% busy at 7 PM;78% busy at 8 PM;65% busy at 9 PM;57% busy at 10 PM;52% busy at 11 PM;52% busy at 12 AM;55% busy at 1 AM;76% busy at 2 AM;84% busy at 3 AM;    36% busy at 4 AM;26% busy at 5 AM;31% busy at 6 AM;50% busy at 7 AM;60% busy at 8 AM;78% busy at 9 AM;78% busy at 10 AM;73% busy at 11 AM;52% busy at 12 PM;47% busy at 1 PM;44% busy at 2 PM;55% busy at 3 PM;60% busy at 4 PM;63% busy at 5 PM;63% busy at 6 PM;63% busy at 7 PM;57% busy at 8 PM;65% busy at 9 PM;50% busy at 10 PM;50% busy at 11 PM;57% busy at 12 AM;47% busy at 1 AM;50% busy at 2 AM;47% busy at 3 AM;    36% busy at 4 AM;39% busy at 5 AM;36% busy at 6 AM;50% busy at 7 AM;47% busy at 8 AM;36% busy at 9 AM;42% busy at 10 AM;50% busy at 11 AM;44% busy at 12 PM;34% busy at 1 PM;34% busy at 2 PM;42% busy at 3 PM;47% busy at 4 PM;47% busy at 5 PM;50% busy at 6 PM;47% busy at 7 PM;52% busy at 8 PM;60% busy at 9 PM;63% busy at 10 PM;76% busy at 11 PM;76% busy at 12 AM;81% busy at 1 AM;73% busy at 2 AM;68% busy at 3 AM;                                                   57% busy at 4 AM;55% busy at 5 AM;63% busy at 6 AM;78% busy at 7 AM;76% busy at 8 AM;60% busy at 9 AM;39% busy at 10 AM;31% busy at 11 AM;50% busy at 12 PM;55% busy at 1 PM;60% busy at 2 PM;44% busy at 3 PM;52% busy at 4 PM;36% busy at 5 PM;42% busy at 6 PM;52% busy at 7 PM;63% busy at 8 PM;71% busy at 9 PM;71% busy at 10 PM;65% busy at 11 PM;76% busy at 12 AM;71% busy at 1 AM;78% busy at 2 AM;60% busy at 3 AM;
1    Coffee shop                                                               Weeks coffee          15.0     4.8                                                                                                  C4W2+2RP, Al Souq, Dammam 32416, Saudi Arabia      SA      Dammam    NaN                                                                                                                                                                                                        NaN                         NaN                                                                                                                                                                                                                                                                                                                                                                                                                                       https://www.google.com/maps/place/Weeks+coffee/data=!4m5!3m4!1s0x3e49fb224fbf4255:0xc4947d58a69ef687!8m2!3d26.4450866!4d50.1020903?authuser=0&hl=en&rclk=1  0x3e49fb224fbf4255:0xc4947d58a69ef687  ChIJVUK_TyL7ST4Rh_aeplh9lMQ                        NaN  26.445087  50.102090        coffee shops                                                                                                                                                            https://lh5.googleusercontent.com/p/AF1QipOmzjr53452EdPODR2KqG0H5annkyxBnUqJfkPc=w408-h544-k-no                        https://lh5.googleusercontent.com/p/AF1QipOmzjr53452EdPODR2KqG0H5annkyxBnUqJfkPc=w1024-h960-p-k-no                        https://lh5.googleusercontent.com/p/AF1QipPvsA4vnEMm2NbRcNmyPjWh3wGwuj9sNCZD_H4c=w1024-h960-p-k-no  https://lh5.googleusercontent.com/p/AF1QipNnrOZKAlCjHYKkmDKzJXt7ZW1OTekbxqivgASS=w1024-h960-p-k-no                                                                                                   NaN    SAR 1–20                 NaN                                                NaN                             NaN                           Delivery                                             NaN                                              NaN                                                NaN                                               NaN                                              NaN                                               NaN                                             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                 NaN                                                                                                                                                                                                                                                                                                                                                                                                                               NaN                                                                                                                                                                                                                                                                                                                                                                                                                               NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NaN                                                                                                                                                                                                                                                                                                                                                                                                                               NaN                                                                                                                                                                                                                                                                                                                                                                                                                               NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                              NaN

In [72]:
print(df.isnull().sum())

keyword                      0
Title                        0
Review_Count                39
Rating                      39
Address                      0
Country                      0
City                         0
State                      552
Website                    264
Phone                      222
Open_Time                    0
Page_URL                     0
Google_id                    0
Place_id                     0
Additional_info            541
Latitude                     0
Longitude                    0
Category                     0
Main_image                  53
Image_1                     57
Image_2                     82
Image_3                    132
Description                509
Price_Range                210
Current_Status             507
Plus_code_URL              109
Plus_code                  109
Delivery                    53
Open_Time_Monday           130
Open_Time_Tuesday          130
Open_Time_Wednesday        130
Open_Time_Thursday         130
Open_Time_Friday           130
Open_Time_Saturday         130
Open_Time_Sunday           130
Popular_times_Monday       259
Popular_times_Tuesday      259
Popular_times_Wednesday    259
Popular_times_Thursday     259
Popular_times_Friday       259
Popular_times_Saturday     259
Popular_times_Sunday       259
dtype: int64

In [73]:
import pandas as pd
from fuzzywuzzy import fuzz
from geopy.distance import geodesic
from itertools import combinations



# Function to calculate Haversine Distance (geo distance between two locations)
def is_nearby(lat1, lon1, lat2, lon2, threshold=0.5):
    """Returns True if two locations are within 'threshold' km."""
    return geodesic((lat1, lon1), (lat2, lon2)).km <= threshold

# Function for fuzzy name matching
def is_similar(name1, name2, threshold=85):
    """Returns True if two names are at least 'threshold'% similar."""
    return fuzz.token_sort_ratio(name1, name2) >= threshold

# Identify possible duplicate restaurants
duplicates = []

for (i, row1), (j, row2) in combinations(df.iterrows(), 2):
    if is_similar(row1["Title"], row2["Title"]) and is_nearby(row1["Latitude"], row1["Longitude"], row2["Latitude"], row2["Longitude"]):
        duplicates.append({
            "Duplicate_1_Index": i,
            "Duplicate_2_Index": j,
            "Duplicate_1_ID": row1["Place_id"],
            "Duplicate_2_ID": row2["Place_id"],
            "Name_1": row1["Title"],
            "Name_2": row2["Title"],
            "Latitude_1": row1["Latitude"],
            "Longitude_1": row1["Longitude"],
            "Latitude_2": row2["Latitude"],
            "Longitude_2": row2["Longitude"]
        })

# Create a DataFrame of duplicate pairs
duplicates_df = pd.DataFrame(duplicates)

# Print detected duplicates
print(f"Found {len(duplicates_df)} potential duplicate restaurants.")
print(duplicates_df.head())

Found 2 potential duplicate restaurants.
   Duplicate_1_Index  Duplicate_2_Index               Duplicate_1_ID  \
0                643                654  ChIJTTdUU43DST4Rh7RN0SaDn-I
1                651                652  ChIJG7oyjE7DST4RGsr88lTex6M

                Duplicate_2_ID                   Name_1  \
0  ChIJ0ZzwGgPDST4RxYiq9TkIwDA  Road Café | قهوة الطريق
1  ChIJ9_LjDMHDST4R4L9WaiGG010              Tim Hortons

                    Name_2  Latitude_1  Longitude_1  Latitude_2  Longitude_2
0  Road Café | قهوة الطريق   26.231834    50.194249   26.230060    50.195494
1              Tim Hortons   26.229843    50.195533   26.231441    50.193929

In [75]:
display(duplicates_df)

,Duplicate_1_Index,Duplicate_2_Index,Duplicate_1_ID,Duplicate_2_ID,Name_1,Name_2,Latitude_1,Longitude_1,Latitude_2,Longitude_2
0,643,654,ChIJTTdUU43DST4Rh7RN0SaDn-I,ChIJ0ZzwGgPDST4RxYiq9TkIwDA,Road Café | قهوة الطريق,Road Café | قهوة الطريق,26.231834,50.194249,26.230060,50.195494
1,651,652,ChIJG7oyjE7DST4RGsr88lTex6M,ChIJ9_LjDMHDST4R4L9WaiGG010,Tim Hortons,Tim Hortons,26.229843,50.195533,26.231441,50.193929

In [76]:
filtered_rows = df[df["Place_id"].isin(['ChIJTTdUU43DST4Rh7RN0SaDn-I', 'ChIJ0ZzwGgPDST4RxYiq9TkIwDA', 'ChIJG7oyjE7DST4RGsr88lTex6M', 'ChIJ9_LjDMHDST4R4L9WaiGG010'])]
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)        # No line width limit
filtered_rows

,keyword,Title,Review_Count,Rating,Address,Country,City,State,Website,Phone,Open_Time,Page_URL,Google_id,Place_id,Additional_info,Latitude,Longitude,Category,Main_image,Image_1,Image_2,Image_3,Description,Price_Range,Current_Status,Plus_code_URL,Plus_code,Delivery,Open_Time_Monday,Open_Time_Tuesday,Open_Time_Wednesday,Open_Time_Thursday,Open_Time_Friday,Open_Time_Saturday,Open_Time_Sunday,Popular_times_Monday,Popular_times_Tuesday,Popular_times_Wednesday,Popular_times_Thursday,Popular_times_Friday,Popular_times_Saturday,Popular_times_Sunday
643,Coffee shop,Road Café | قهوة الطريق,35.0,4.2,"حي, التعاون،،, EEGA7934، 7934 طريق الملك خالد ...",SA,Al Khobar,NaN,https://roadcafe.com/,+966 50 624 0568,Monday Open 24 hours 2025-03-31\r\nTuesday Op...,https://www.google.com/maps/place/Road+Café+|+...,0x3e49c38d5354374d:0xe29f8326d14db487,ChIJTTdUU43DST4Rh7RN0SaDn-I,NaN,26.231834,50.194249,coffee shops,https://lh3.googleusercontent.com/p/AF1QipNNNR...,https://lh5.googleusercontent.com/p/AF1QipNNNR...,https://lh5.googleusercontent.com/p/AF1QipNNNR...,https://lh5.googleusercontent.com/p/AF1QipNNNR...,NaN,SAR 20–40,NaN,https://plus.codes/65JV+PM Al Khobar Saudi Arabia,65JV+PM Al Khobar Saudi Arabia,Drive-through,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-04-06,18% busy at 4 AM;18% busy at 5 AM;25% busy at ...,56% busy at 4 AM;56% busy at 5 AM;62% busy at ...,6% busy at 4 AM;18% busy at 5 AM;25% busy at 6...,68% busy at 4 AM;31% busy at 5 AM;18% busy at ...,100% busy at 4 AM;68% busy at 5 AM;68% busy at...,31% busy at 4 AM;12% busy at 5 AM;18% busy at ...,18% busy at 4 AM;6% busy at 5 AM;12% busy at 6...
651,Coffee shop,Tim Hortons,18.0,4.3,"2117 طريق الملك خالد فرعي, 65HW+X8, حي الحمراء...",SA,Al Khobar,NaN,https://timhortonsgcc.com/,+966 56 109 8428,Monday Open 24 hours 2025-03-31\r\nTuesday Op...,https://www.google.com/maps/place/Tim+Hortons/...,0x3e49c34e8c32ba1b:0xa3c7de54f2fcca1a,ChIJG7oyjE7DST4RGsr88lTex6M,NaN,26.229843,50.195533,coffee shops,https://lh5.googleusercontent.com/p/AF1QipP-Du...,https://lh5.googleusercontent.com/p/AF1QipMoDY...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 20–40,NaN,https://plus.codes/65HW+W6 Al Khobar Saudi Arabia,65HW+W6 Al Khobar Saudi Arabia,Delivery,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-04-06,53% busy at 4 AM;76% busy at 5 AM;72% busy at ...,32% busy at 4 AM;34% busy at 5 AM;44% busy at ...,37% busy at 4 AM;37% busy at 5 AM;58% busy at ...,74% busy at 4 AM;88% busy at 5 AM;72% busy at ...,67% busy at 4 AM;53% busy at 5 AM;51% busy at ...,46% busy at 4 AM;46% busy at 5 AM;37% busy at ...,46% busy at 4 AM;48% busy at 5 AM;48% busy at ...
652,Coffee shop,Tim Hortons,123.0,4.2,"Al Thawn, Al Khobar 34632, Saudi Arabia",SA,Al Khobar,NaN,https://timhortonsgcc.com/,+966 55 964 8403,Monday Open 24 hours 2025-03-31\r\nTuesday Op...,https://www.google.com/maps/place/Tim+Hortons/...,0x3e49c3c10ce3f2f7:0x5dd386216a56bfe0,ChIJ9_LjDMHDST4R4L9WaiGG010,NaN,26.231441,50.193929,coffee shops,https://lh5.googleusercontent.com/p/AF1QipPyQy...,https://lh5.googleusercontent.com/p/AF1QipPwG0...,https://lh5.googleusercontent.com/p/AF1QipMsE2...,https://lh5.googleusercontent.com/p/AF1QipMNRu...,Canadian chain for signature premium-blend cof...,SAR 20–40,NaN,https://plus.codes/65JV+HH Al Khobar Saudi Arabia,65JV+HH Al Khobar Saudi Arabia,Delivery,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-04-06,37% busy at 4 AM;50% busy at 5 AM;56% busy at ...,31% busy at 4 AM;25% busy at 5 AM;25% busy at ...,37% busy at 4 AM;50% busy at 5 AM;56% busy at ...,25% busy at 4 AM;62% busy at 5 AM;75% busy at ...,56% busy at 4 AM;56% busy at 5 AM;56% busy at ...,25% busy at 4 AM;18% busy at 5 AM;37% busy at ...,18% busy at 4 AM;31% busy at 5 AM;43% busy at ...
654,Coffee shop,Road Café | قهوة الطريق,4.0,3.3,"King Khalid Rd, فرعي, EEDA7369، 7369 ، 2117، ح...",SA,Al Khobar,NaN,http://roadcafe.com/,+966 50 624 0568,Monday Open 24 hours 2025-03-31\r\nTuesday Op...,https://www.google.com/maps/place/Road+Café+|+...,0x3e49c3031af09cd1:0x30c00839f5aa88c5,ChIJ0ZzwGgPDST4RxYiq9TkIwDA,NaN,26.230060,50.195494,coffee shops,https://lh5.googleusercontent.com/p/AF1QipNuG5...,https://lh5.googleusercontent.com/p/AF1QipNuG5...,https://lh5.googleusercontent.com/p/AF1QipMVNx...,NaN,NaN,$$,NaN,https://plus.codes/65JW+25 Al Khobar Saudi Arabia,65JW+25 Al Khobar Saudi Arabia,No-contact delivery,Monday Open 24 hours 2025-03-31,Tuesday Open 24 hours 2025-04-01,Wednesday Open 24 hours 2025-04-02,Thursday Open 24 hours 2025-04-03,Friday Open 24 hours 2025-04-04,Saturday Open 24 hours 2025-04-05,Sunday Open 24 hours 2025-04-06,33% busy at 4 AM;53% busy at 5 AM;33% busy at ...,46% busy at 4 AM;46% busy at 5 AM;53% busy at ...,60% busy at 4 AM;86% busy at 5 AM;93% busy at ...,53% busy at 4 AM;73% busy at 5 AM;80% busy at ...,20% busy at 4 AM;13% busy at 5 AM;26% busy at ...,40% busy at 4 AM;53% busy at 5 AM;40% busy at ...,40% busy at 4 AM;53% busy at 5 AM;60% busy at ...

In [77]:
df = df[~df["Place_id"].isin(['ChIJ0ZzwGgPDST4RxYiq9TkIwDA','ChIJG7oyjE7DST4RGsr88lTex6M'])]

In [78]:
df.to_csv("cleaned_Octoparse_coffeshops.csv", index=False)