In [62]:
import pandas as pd

In [63]:
df1 = pd.read_csv("../../../Collected Data/Octoparse_AllBusinesses/Dammam Restaurant.csv")
df2 = pd.read_csv("../../../Collected Data/Octoparse_AllBusinesses/Dhahran Restaurant.csv")
df3 = pd.read_csv("../../../Collected Data/Octoparse_AllBusinesses/Khobar Restaurant.csv")
df = pd.concat([df1, df2, df3], ignore_index=True)

In [64]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   keyword                  675 non-null    object
 1   Title                    675 non-null    object
 2   Review_Count             646 non-null    float64
 3   Rating                   646 non-null    float64
 4   Address                  675 non-null    object
 5   Country                  675 non-null    object
 6   City                     675 non-null    object
 7   State                    0 non-null      float64
 8   Website                  172 non-null    object
 9   Phone                    507 non-null    object
 10  Open_Time                675 non-null    object
 11  Page_URL                 675 non-null    object
 12  Google_id                675 non-null    object
 13  Place_id                 675 non-null    object
 14  Additional_info          16 non-null     object
 15  Latitude                 675 non-null    float64
 16  Longitude                675 non-null    float64
 17  Category                 675 non-null    object
 18  Main_image               636 non-null    object
 19  Image_1                  634 non-null    object
 20  Image_2                  612 non-null    object
 21  Image_3                  552 non-null    object
 22  Description              16 non-null     object
 23  Price_Range              421 non-null    object
 24  Current_Status           30 non-null     object
 25  Plus_code_URL            507 non-null    object
 26  Plus_code                507 non-null    object
 27  Delivery                 617 non-null    object
 28  Open_Time_Monday         496 non-null    object
 29  Open_Time_Tuesday        496 non-null    object
 30  Open_Time_Wednesday      496 non-null    object
 31  Open_Time_Thursday       496 non-null    object
 32  Open_Time_Friday         496 non-null    object
 33  Open_Time_Saturday       496 non-null    object
 34  Open_Time_Sunday         496 non-null    object
 35  Popular_times_Monday     415 non-null    object
 36  Popular_times_Tuesday    415 non-null    object
 37  Popular_times_Wednesday  415 non-null    object
 38  Popular_times_Thursday   415 non-null    object
 39  Popular_times_Friday     415 non-null    object
 40  Popular_times_Saturday   415 non-null    object
 41  Popular_times_Sunday     415 non-null    object
dtypes: float64(5), object(37)
memory usage: 221.6+ KB

,keyword,Title,Review_Count,Rating,Address,Country,City,State,Website,Phone,Open_Time,Page_URL,Google_id,Place_id,Additional_info,Latitude,Longitude,Category,Main_image,Image_1,Image_2,Image_3,Description,Price_Range,Current_Status,Plus_code_URL,Plus_code,Delivery,Open_Time_Monday,Open_Time_Tuesday,Open_Time_Wednesday,Open_Time_Thursday,Open_Time_Friday,Open_Time_Saturday,Open_Time_Sunday,Popular_times_Monday,Popular_times_Tuesday,Popular_times_Wednesday,Popular_times_Thursday,Popular_times_Friday,Popular_times_Saturday,Popular_times_Sunday
0,Restaurant,Pattis france,5405.0,4.3,"Prince Turkey Street, Al Khobar Al Shamalia, A...",SA,Al Khobar,NaN,http://www.pattis.com.sa/,+966 13 881 8224,Monday 7 AM–12 AM 2025-03-31\r\nTuesday 7 AM–...,https://www.google.com/maps/place/Pattis+franc...,0x3e49e8ee00ad85f3:0x4dce007d833042de,ChIJ84WtAO7oST4R3kIwg30Azk0,NaN,26.288333,50.219416,restaurants,https://lh5.googleusercontent.com/p/AF1QipPFZZ...,https://lh5.googleusercontent.com/p/AF1QipNgNI...,https://lh5.googleusercontent.com/p/AF1QipNYK5...,https://lh5.googleusercontent.com/p/AF1QipMBp7...,Elevated international dishes & drinks present...,$$$,NaN,https://plus.codes/76Q9+8Q Al Khobar Saudi Arabia,76Q9+8Q Al Khobar Saudi Arabia,No-contact delivery,Monday 7 AM–12 AM 2025-03-31,Tuesday 7 AM–12 AM 2025-04-01,Wednesday 7 AM–12 AM 2025-04-02,Thursday 7 AM–12 AM 2025-04-03,Friday 7 AM–12 AM 2025-04-04,Saturday 7 AM–12 AM 2025-04-05,Sunday 7 AM–12 AM 2025-04-06,0% busy at 6 AM;17% busy at 7 AM;22% busy at 8...,0% busy at 6 AM;15% busy at 7 AM;18% busy at 8...,0% busy at 6 AM;23% busy at 7 AM;25% busy at 8...,0% busy at 6 AM;17% busy at 7 AM;21% busy at 8...,0% busy at 6 AM;26% busy at 7 AM;35% busy at 8...,0% busy at 6 AM;18% busy at 7 AM;30% busy at 8...,0% busy at 6 AM;17% busy at 7 AM;23% busy at 8...
1,Restaurant,Chettinad Restaurant,482.0,4.1,"7922 الامير ناصر بن عبد العزيز, حي العدامة, ED...",SA,Dammam,NaN,NaN,+966 59 108 8097,Monday 7 AM–11:30 PM 2025-03-31\r\nTuesday 7 ...,https://www.google.com/maps/place/Chettinad+Re...,0x3e49fb12c08a1287:0x38be45309d63ef75,ChIJhxKKwBL7ST4Rde9jnTBFvjg,NaN,26.436642,50.107418,South Indian restaurant,https://lh5.googleusercontent.com/p/AF1QipNftX...,https://lh5.googleusercontent.com/p/AF1QipOEp4...,https://lh5.googleusercontent.com/p/AF1QipNWEL...,https://lh5.googleusercontent.com/p/AF1QipOx8Q...,NaN,SAR 1–20,NaN,https://plus.codes/C4P4+MX Dammam Saudi Arabia,C4P4+MX Dammam Saudi Arabia,Delivery,Monday 7 AM–11:30 PM 2025-03-31,Tuesday 7 AM–11:30 PM 2025-04-01,Wednesday 7 AM–11:30 PM 2025-04-02,Thursday 7 AM–11:30 PM 2025-04-03,Friday 7 AM–11:30 PM 2025-04-04,Saturday 7 AM–11:30 PM 2025-04-05,Sunday 7 AM–11:30 PM 2025-04-06,0% busy at 6 AM;27% busy at 7 AM;31% busy at 8...,0% busy at 6 AM;22% busy at 7 AM;24% busy at 8...,0% busy at 6 AM;30% busy at 7 AM;29% busy at 8...,0% busy at 6 AM;27% busy at 7 AM;30% busy at 8...,0% busy at 6 AM;27% busy at 7 AM;36% busy at 8...,0% busy at 6 AM;34% busy at 7 AM;41% busy at 8...,0% busy at 6 AM;28% busy at 7 AM;34% busy at 8...
2,Restaurant,Galaxy Restaurant,355.0,4.0,"C3CP+6V9, 2 St, Al Badiyah, Dammam 32243, Saud...",SA,Dammam,NaN,NaN,+966 54 924 4011,Monday 6 AM–12 AM 2025-03-31\r\nTuesday 6 AM–...,https://www.google.com/maps/place/Galaxy+Resta...,0x3e49fc8e38318541:0x75ad9582893e8a3c,ChIJQYUxOI78ST4RPIo-iYKVrXU,NaN,26.420537,50.087247,restaurants,https://lh5.googleusercontent.com/p/AF1QipMms6...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 1–20,NaN,NaN,NaN,Delivery,Monday 6 AM–12 AM 2025-03-31,Tuesday 6 AM–12 AM 2025-04-01,Wednesday 6 AM–12 AM 2025-04-02,Thursday 6 AM–12:30 AM 2025-04-03,Friday 5:30 AM–12 AM 2025-04-04,Saturday 6 AM–12 AM 2025-04-05,Sunday 6 AM–12 AM 2025-04-06,0% busy at 5 AM;71% busy at 6 AM;83% busy at 7...,0% busy at 5 AM;61% busy at 6 AM;80% busy at 7...,0% busy at 5 AM;73% busy at 6 AM;84% busy at 7...,0% busy at 5 AM;71% busy at 6 AM;86% busy at 7...,0% busy at 4 AM;16% busy at 5 AM;31% busy at 6...,0% busy at 5 AM;56% busy at 6 AM;78% busy at 7...,0% busy at 5 AM;67% busy at 6 AM;89% busy at 7...
3,Restaurant,OLIVE DAMMAM RESTAURANT,82.0,4.1,Dammam Seiko Saudi Arabia,SA,Dammam,NaN,NaN,+966 53 137 3030,Monday 4 AM–12 AM 2025-03-31\r\nTuesday 4 AM–...,https://www.google.com/maps/place/OLIVE+DAMMAM...,0x3e49fd10652a6d3d:0x83229800f0c13d73,ChIJPW0qZRD9ST4Rcz3B8ACYIoM,NaN,26.440794,50.099697,restaurants,https://lh5.googleusercontent.com/p/AF1QipM0Fn...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 1–20,NaN,https://plus.codes/C3RX+8V Dammam Saudi Arabia,C3RX+8V Dammam Saudi Arabia,Delivery,Monday 4 AM–12 AM 2025-03-31,Tuesday 4 AM–12 AM 2025-04-01,Wednesday 4 AM–12 AM 2025-04-02,Thursday 4 AM–12 AM 2025-04-03,Friday 4 AM–12 AM 2025-04-04,Saturday 4 AM–12 AM 2025-04-05,Sunday 4 AM–12 AM 2025-04-06,0% busy at 3 AM;20% busy at 4 AM;37% busy at 5...,0% busy at 3 AM;8% busy at 4 AM;20% busy at 5 ...,0% busy at 3 AM;20% busy at 4 AM;25% busy at 5...,0% busy at 3 AM;33% busy at 4 AM;33% busy at 5...,0% busy at 3 AM;20% busy at 4 AM;16% busy at 5...,0% busy at 3 AM;8% busy at 4 AM;8% busy at 5 A...,0% busy at 3 AM;37% busy at 4 AM;33% busy at 5...
4,Restaurant,INDIAN RESTAURANT,135.0,3.9,"65CM+GHF, Al Thawn, Al Khobar 34632, Saudi Arabia",SA,Al Khobar,NaN,NaN,NaN,,https://www.google.com/maps/place/INDIAN+RESTA...,0x3e49c38e88053457:0xb37416307389cf53,ChIJVzQFiI7DST4RU8-JczAWdLM,NaN,26.221308,50.183925,restaurants,https://lh5.googleusercontent.com/p/AF1QipN6lo...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 1–20,NaN,NaN,NaN,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
#Check business status counts ??? we don't have it 
#status_counts_df = df['Business Status'].value_counts().reset_index()
#status_counts_df.columns = ['Business Status', 'Count']
#print(status_counts_df)

In [66]:
# Check for duplicates in the 'Google_id column'
duplicates = df[df.duplicated(subset=['Google_id'], keep=False)]

# Display duplicates
duplicates

,keyword,Title,Review_Count,Rating,Address,Country,City,State,Website,Phone,Open_Time,Page_URL,Google_id,Place_id,Additional_info,Latitude,Longitude,Category,Main_image,Image_1,Image_2,Image_3,Description,Price_Range,Current_Status,Plus_code_URL,Plus_code,Delivery,Open_Time_Monday,Open_Time_Tuesday,Open_Time_Wednesday,Open_Time_Thursday,Open_Time_Friday,Open_Time_Saturday,Open_Time_Sunday,Popular_times_Monday,Popular_times_Tuesday,Popular_times_Wednesday,Popular_times_Thursday,Popular_times_Friday,Popular_times_Saturday,Popular_times_Sunday
0,Restaurant,Pattis france,5405.0,4.3,"Prince Turkey Street, Al Khobar Al Shamalia, A...",SA,Al Khobar,NaN,http://www.pattis.com.sa/,+966 13 881 8224,Monday 7 AM–12 AM 2025-03-31\r\nTuesday 7 AM–...,https://www.google.com/maps/place/Pattis+franc...,0x3e49e8ee00ad85f3:0x4dce007d833042de,ChIJ84WtAO7oST4R3kIwg30Azk0,NaN,26.288333,50.219416,restaurants,https://lh5.googleusercontent.com/p/AF1QipPFZZ...,https://lh5.googleusercontent.com/p/AF1QipNgNI...,https://lh5.googleusercontent.com/p/AF1QipNYK5...,https://lh5.googleusercontent.com/p/AF1QipMBp7...,Elevated international dishes & drinks present...,$$$,NaN,https://plus.codes/76Q9+8Q Al Khobar Saudi Arabia,76Q9+8Q Al Khobar Saudi Arabia,No-contact delivery,Monday 7 AM–12 AM 2025-03-31,Tuesday 7 AM–12 AM 2025-04-01,Wednesday 7 AM–12 AM 2025-04-02,Thursday 7 AM–12 AM 2025-04-03,Friday 7 AM–12 AM 2025-04-04,Saturday 7 AM–12 AM 2025-04-05,Sunday 7 AM–12 AM 2025-04-06,0% busy at 6 AM;17% busy at 7 AM;22% busy at 8...,0% busy at 6 AM;15% busy at 7 AM;18% busy at 8...,0% busy at 6 AM;23% busy at 7 AM;25% busy at 8...,0% busy at 6 AM;17% busy at 7 AM;21% busy at 8...,0% busy at 6 AM;26% busy at 7 AM;35% busy at 8...,0% busy at 6 AM;18% busy at 7 AM;30% busy at 8...,0% busy at 6 AM;17% busy at 7 AM;23% busy at 8...
4,Restaurant,INDIAN RESTAURANT,135.0,3.9,"65CM+GHF, Al Thawn, Al Khobar 34632, Saudi Arabia",SA,Al Khobar,NaN,NaN,NaN,,https://www.google.com/maps/place/INDIAN+RESTA...,0x3e49c38e88053457:0xb37416307389cf53,ChIJVzQFiI7DST4RU8-JczAWdLM,NaN,26.221308,50.183925,restaurants,https://lh5.googleusercontent.com/p/AF1QipN6lo...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 1–20,NaN,NaN,NaN,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Restaurant,Salkara Family Restaurant,3264.0,4.0,"Al Khoubar, Al Khobar Al Janubiyah, Al Khobar ...",SA,Al Khobar,NaN,http://www.mysalkara.com/,+966 59 000 3428,Monday 6 AM–11:30 PM 2025-03-31\r\nTuesday 6 ...,https://www.google.com/maps/place/Salkara+Fami...,0x3e49e8188197fecb:0x4f9b5c43689d0129,ChIJy_6XgRjoST4RKQGdaENcm08,NaN,26.278311,50.203667,restaurants,https://lh5.googleusercontent.com/p/AF1QipMjEv...,https://lh5.googleusercontent.com/p/AF1QipPTMA...,https://lh5.googleusercontent.com/p/AF1QipMMTs...,https://lh5.googleusercontent.com/p/AF1QipPpp6...,Unassuming option fixing up South Indian stapl...,SAR 20–40,NaN,https://plus.codes/76H3+8F Al Khobar Saudi Arabia,76H3+8F Al Khobar Saudi Arabia,Delivery,Monday 6 AM–11:30 PM 2025-03-31,Tuesday 6 AM–11:30 PM 2025-04-01,Wednesday 6 AM–11:30 PM 2025-04-02,Thursday 6 AM–11:30 PM 2025-04-03,Friday 6 AM–11:30 PM 2025-04-04,Saturday 6 AM–11:30 PM 2025-04-05,Sunday 6 AM–11:30 PM 2025-04-06,0% busy at 5 AM;24% busy at 6 AM;31% busy at 7...,0% busy at 5 AM;26% busy at 6 AM;33% busy at 7...,0% busy at 5 AM;24% busy at 6 AM;30% busy at 7...,0% busy at 5 AM;25% busy at 6 AM;31% busy at 7...,0% busy at 5 AM;16% busy at 6 AM;28% busy at 7...,0% busy at 5 AM;22% busy at 6 AM;33% busy at 7...,0% busy at 5 AM;20% busy at 6 AM;25% busy at 7...
12,Restaurant,Thaza Restaurant,762.0,3.9,"حي, 7215 الشارع الخامس والعشرين، 5084, Al Khob...",SA,Al Khobar,NaN,NaN,NaN,Monday 5 AM–11:50 PM 2025-03-31\r\nTuesday 5 ...,https://www.google.com/maps/place/Thaza+Restau...,0x3e49c3a96ea818bd:0x9bceb3928341f6a5,ChIJvRiobqnDST4RpfZBg5Kzzps,NaN,26.269620,50.206367,Corporate office,https://lh5.googleusercontent.com/p/AF1QipPnFW...,https://lh5.googleusercontent.com/p/AF1QipOG1r...,https://lh5.googleusercontent.com/p/AF1QipO993...,https://lh5.googleusercontent.com/p/AF1QipOswF...,NaN,$$,NaN,https://plus.codes/7694+RG Al Khobar Saudi Arabia,7694+RG Al Khobar Saudi Arabia,NaN,Monday 5 AM–11:50 PM 2025-03-31,Tuesday 5 AM–11:50 PM 2025-04-01,Wednesday 5 AM–11:50 PM 2025-04-02,Thursday 5 AM–11:50 PM 2025-04-03,Friday 5 AM–11:50 PM 2025-04-04,Saturday 5 AM–11:50 PM 2025-04-05,Sunday 5 AM–11:50 PM 2025-04-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Restaurant,THAAL RESTAURANT,91.0,4.1,"27 Cross, Prince Fawaz Bin Abdulaziz St, Al Kh...",SA,Al Khobar,NaN,NaN,+966 53 978 6500,Monday 5:30 AM–11:30 PM 2025-03-31\r\nTuesday...,https://www.google.com/maps/place/THAAL+RESTAU...,0x3e49e9615db67d15:0x467b15d3c6592b6f,ChIJFX22XWHpST4RbytZxtMVe0Y,NaN,26.301184,50.210857,restaurants,https://lh5.googleusercontent.com/p/AF1QipPeqm...,https://lh5.googleusercontent.com/p/AF1QipP-Gt...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 1–20,NaN,https://plus.codes/8626+F8 Al Khobar Saudi Arabia,8626+F8 Al Khobar Saudi Arabia,No-contact delivery,Monday 5:30 AM–11:30 PM 2025-03-31,Tuesday 5:30 AM–11:30 PM 2025-04-01,Wednesday 5:30 AM–11:30 PM 2025-04-02,Thursday 5:30 AM–11:30 PM 2025-04-03,Friday 5:30 AM–11:30 PM 2025-04-04,Saturday 5:30 AM–11:30 PM 2025-04-05,Sunday 5:30 AM–11:30 PM 2025-04-06,0% busy at 4 AM;24% busy at 5 AM;41% busy at 6...,0% busy at 4 AM;24% busy at 5 AM;44% busy at 6...,0% busy at 4 AM;26% busy at 5 AM;44% busy at 6...,0% busy at 4 AM;25% busy at 5 AM;44% busy at 6...,0% busy at 4 AM;15% busy at 5 AM;23% busy at 6...,0% busy at 4 AM;25% busy at 5 AM;39% busy at 6...,0% busy at 4 AM;25% busy at 5 AM;41% busy at 6...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,Restaurant,Halo restaurant,6.0,3.0,"76P6+VVJ, King Abdullah St, Al Khobar Al Shama...",SA,Al Khobar,NaN,NaN,+966 56 282 5404,,https://www.google.com/maps/place/Halo+restaur...,0x3e49e99356b29a0b:0x958769aaebf57a9e,ChIJC5qyVpPpST4Rnnr166pph5U,NaN,26.287207,50.212139,restaurants,https://lh5.googleusercontent.com/p/AF1QipOcRv...,https://lh5.googleusercontent.com/p/AF1QipOcRv...,https://lh5.googleusercontent.com/p/AF1QipPUIg...,NaN,NaN,NaN,Temporarily closed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,Restaurant,Zilal Al Nahr Restaurant,3.0,2.3,"6712 الدار قطني،, Al Sheraa, 4806, Al Khobar 3...",SA,Al Khobar,NaN,NaN,+966 55 221 2436,,https://www.google.com/maps/place/Zilal+Al+Nah...,0x3e49db47d35ce455:0xdbc46e5174a5a5f1,ChIJVeRc00fbST4R8aWldFFuxNs,NaN,26.155707,50.137304,restaurants,https://lh5.googleusercontent.com/p/AF1QipNWlI...,https://lh5.googleusercontent.com/p/AF1QipNWlI...,NaN,NaN,NaN,NaN,NaN,https://plus.codes/544P+7W Al Khobar Saudi Arabia,544P+7W Al Khobar Saudi Arabia,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,Restaurant,Al Badar Restaurant,19.0,4.0,"75JQ+5WW, Yanbu St, Al-Thuqbah, Al Khobar 3462...",SA,Al Khobar,NaN,NaN,+966 55 078 7557,,https://www.google.com/maps/place/Al+Badar+Res...,0x3e49e80e97f4ffff:0x89164f670c37fc06,ChIJ___0lw7oST4RBvw3DGdPFok,NaN,26.280496,50.189842,restaurants,https://lh3.googleusercontent.com/gps-cs-s/AB5...,https://lh5.googleusercontent.com/p/AF1QipMoBw...,https://lh5.googleusercontent.com/p/AF1QipOtw7...,https://lh5.googleusercontent.com/p/AF1QipPhJx...,NaN,NaN,NaN,NaN,NaN,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
655,Restaurant,Rawan Bukhari Restaurant,490.0,4.0,"Al Kawthar, Al Khobar 34753, Saudi Arabia",SA,Al Khobar,NaN,NaN,+966 53 505 2139,Monday 9:30 AM–11 PM 2025-03-31\r\nTuesday 9:...,https://www.google.com/maps/place/Rawan+Bukhar...,0x3e49dbf310472961:0x49048bb1bbb4e174,ChIJYSlHEPPbST4RdOG0u7GLBEk,NaN,26.157620,50.119678,restaurants,https://lh5.googleusercontent.com/p/AF1QipNzU9...,https://lh5.googleusercontent.com/p/AF1QipOzsN...,https://lh5.googleusercontent.com/p/AF1QipN5mg...,https://lh5.googleusercontent.com/p/AF1QipPYi2...,NaN,SAR 1–20,NaN,https://plus.codes/5459+2V Al Khobar Saudi Arabia,5459+2V Al Khobar Saudi Arabia,Delivery,Monday 9:30 AM–11 PM 2025-03-31,Tuesday 9:30 AM–11 PM 2025-04-01,Wednesday 9:30 AM–11 PM 2025-04-02,Thursday 9:30 AM–11 PM 2025-04-03,Friday 1 PM–12 AM 2025-04-04,Saturday 9:30 AM–11 PM 2025-04-05,Sunday 9:30 AM–11 PM 2025-04-06,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...
672,Restaurant,Shalloum Golden Restaurant,6.0,1.5,"4th St, Al-Thuqbah, Taif st, Al Khobar 34623, ...",SA,Al Khobar,NaN,NaN,+966 55 271 0885,Monday 6:30 AM–1 AM 2025-03-31\r\nTuesday 6:3...,https://www.google.com/maps/place/Shalloum+Gol...,0x3e49e944cfa6501f:0x9bd9b57e83457c19,ChIJH1Cmz0TpST4RGXxFg3612Zs,NaN,26.284326,50.184512,Shawarma restaurant,https://lh3.googleusercontent.com/gps-cs-s/AB5...,https://lh5.googleusercontent.com/p/AF1QipMTMy...,https://lh5.googleusercontent.com/p/AF1QipNbZD...,NaN,NaN,NaN,NaN,https://plus.codes/75MM+PR Al Khobar Saudi Arabia,75MM+PR Al Khobar Saudi Arabia,No-contact delivery,Monday 6:30 AM–1 AM 2025-03-31,Tuesday 6:30 AM–1 AM 2025-04-01,Wednesday 6:30 AM–1 AM 2025-04-02,Thursday 6:30 AM–1 AM 2025-04-03,Friday 12 PM–1 AM 2025-04-04,Saturday 6:30 AM–1 AM 2025-04-05,Sunday 6:30 AM–1 AM 2025-04-06,0% busy at 5 AM;61% busy at 6 AM;46% busy at 7...,0% busy at 5 AM;46% busy at 6 AM;30% busy at 7...,0% busy at 5 AM;53% busy at 6 AM;46% busy at 7...,0% busy at 5 AM;76% busy at 6 AM;30% busy at 7...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 5 AM;69% busy at 6 AM;53% busy at 7...,0% busy at 5 AM;38% busy at 6 AM;23% busy at 7...

In [67]:
# drop all occurunces except the first one
df = df.drop_duplicates(subset=['Google_id'], keep="first")
df.count()

keyword                    622
Title                      622
Review_Count               593
Rating                     593
Address                    622
Country                    622
City                       622
State                        0
Website                    159
Phone                      464
Open_Time                  622
Page_URL                   622
Google_id                  622
Place_id                   622
Additional_info             15
Latitude                   622
Longitude                  622
Category                   622
Main_image                 583
Image_1                    581
Image_2                    560
Image_3                    502
Description                 12
Price_Range                378
Current_Status              23
Plus_code_URL              467
Plus_code                  467
Delivery                   573
Open_Time_Monday           459
Open_Time_Tuesday          459
Open_Time_Wednesday        459
Open_Time_Thursday         459
Open_Time_Friday           459
Open_Time_Saturday         459
Open_Time_Sunday           459
Popular_times_Monday       383
Popular_times_Tuesday      383
Popular_times_Wednesday    383
Popular_times_Thursday     383
Popular_times_Friday       383
Popular_times_Saturday     383
Popular_times_Sunday       383
dtype: int64

In [68]:
pip install folium geopy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: folium in c:\users\farah\appdata\roaming\python\python312\site-packages (0.19.4)
Requirement already satisfied: geopy in c:\users\farah\appdata\roaming\python\python312\site-packages (2.4.1)
Requirement already satisfied: pandas in c:\users\farah\appdata\roaming\python\python312\site-packages (2.1.2)
Requirement already satisfied: branca>=0.6.0 in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (1.26.1)
Requirement already satisfied: requests in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\users\farah\appdata\roaming\python\python312\site-packages (from folium) (2025.1.0)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\farah\appdata\roaming\python\python312\site-packages (from geopy) (2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\farah\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\farah\appdata\roaming\python\python312\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\farah\appdata\roaming\python\python312\site-packages (from pandas) (2023.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\farah\appdata\roaming\python\python312\site-packages (from jinja2>=2.9->folium) (2.1.5)
Requirement already satisfied: six>=1.5 in c:\users\farah\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\farah\appdata\roaming\python\python312\site-packages (from requests->folium) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [69]:
#df.insert(0, 'ID', range(0, 0 + len(df)))
#df

In [70]:
import folium
import pandas as pd
from geopy.distance import geodesic


# Create a Folium Map Centered at First Location
m = folium.Map(location=[df["Latitude"].mean(), df["Longitude"].mean()], zoom_start=16)

# Add Markers to Map
for index, row in df.iterrows():
    folium.Marker(
        location=[row["Latitude"], row["Longitude"]],
        popup=[row["Title"], row["Place_id"]],
        icon=folium.Icon(color="blue")  # Mark possible duplicates
    ).add_to(m)

# Save and Display Map
m.save("map.html")
m

In [ ]:
# deleting POIs out of the scope: 
df = df[~df["Place_id"].isin(['ChIJ6amsuUf-ST4RSklte6RiCww','ChIJJco0Xfr_ST4RfXWaJiAtXpk','ChIJKyYA-Fn_ST4R7MkYlB5qEGM','ChIJg_mqdGsBNj4RbuKblcdttes', 'ChIJb7MRIdgBNj4RInlBk6fLEnY'])]

In [72]:
df.count()

keyword                    617
Title                      617
Review_Count               588
Rating                     588
Address                    617
Country                    617
City                       617
State                        0
Website                    156
Phone                      460
Open_Time                  617
Page_URL                   617
Google_id                  617
Place_id                   617
Additional_info             14
Latitude                   617
Longitude                  617
Category                   617
Main_image                 578
Image_1                    576
Image_2                    555
Image_3                    497
Description                 12
Price_Range                376
Current_Status              23
Plus_code_URL              464
Plus_code                  464
Delivery                   569
Open_Time_Monday           455
Open_Time_Tuesday          455
Open_Time_Wednesday        455
Open_Time_Thursday         455
Open_Time_Friday           455
Open_Time_Saturday         455
Open_Time_Sunday           455
Popular_times_Monday       379
Popular_times_Tuesday      379
Popular_times_Wednesday    379
Popular_times_Thursday     379
Popular_times_Friday       379
Popular_times_Saturday     379
Popular_times_Sunday       379
dtype: int64

In [73]:
print(df.to_string())

        keyword                                                                                   Title  Review_Count  Rating                                                                                                                      Address Country        City  State                                                                                                                                                                  Website                       Phone                                                                                                                                                                                                                                                                                                                                                                            Open_Time                                                                                                                                                                                                                           Page_URL                              Google_id                     Place_id            Additional_info   Latitude  Longitude                   Category                                                                                                                                                                                                                                                 Main_image                                                                                                                   Image_1                                                                                                                   Image_2                                                                                             Image_3                                                                                           Description  Price_Range      Current_Status                                                               Plus_code_URL                                                Plus_code             Delivery                               Open_Time_Monday                               Open_Time_Tuesday                               Open_Time_Wednesday                               Open_Time_Thursday                                Open_Time_Friday                               Open_Time_Saturday                                  Open_Time_Sunday                                                                                                                                                                                                                                                                                                                                                                                                             Popular_times_Monday                                                                                                                                                                                                                                                                                                                                                                                                            Popular_times_Tuesday                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Popular_times_Wednesday                                                                                                                                                                                                                                                                                                                                                                                                           Popular_times_Thursday                                                                                                                                                                                                                                                                                                                                                                                                             Popular_times_Friday                                                                                                                                                                                                                                                                                                                                                                                                           Popular_times_Saturday                                                                                                                                                                                                                                                                                                                                                                                                             Popular_times_Sunday
0    Restaurant                                                                           Pattis france        5405.0     4.3                                                   Prince Turkey Street, Al Khobar Al Shamalia, Al Khobar 34427, Saudi Arabia      SA   Al Khobar    NaN                                                                                                                                                http://www.pattis.com.sa/            +966 13 881 8224                                                                                                                                     Monday 7 AM–12 AM  2025-03-31\r\nTuesday 7 AM–12 AM  2025-04-01\r\nWednesday 7 AM–12 AM  2025-04-02\r\nThursday 7 AM–12 AM  2025-04-03\r\nFriday 7 AM–12 AM  2025-04-04\r\nSaturday 7 AM–12 AM  2025-04-05\r\nSunday 7 AM–12 AM  2025-04-06\r\n                                                                         https://www.google.com/maps/place/Pattis+france/data=!4m5!3m4!1s0x3e49e8ee00ad85f3:0x4dce007d833042de!8m2!3d26.2883329!4d50.2194158?authuser=0&hl=en&rclk=1  0x3e49e8ee00ad85f3:0x4dce007d833042de  ChIJ84WtAO7oST4R3kIwg30Azk0                        NaN  26.288333  50.219416                restaurants                                                                                                                                                            https://lh5.googleusercontent.com/p/AF1QipPFZZDrJMKdYiLY17dI5YmcCS20v6mVu4EkmOw8=w408-h306-k-no                        https://lh5.googleusercontent.com/p/AF1QipNgNINZG0XER1MbbOTBGbvtRtIHRcfITiEWJSjq=w1024-h960-p-k-no                        https://lh5.googleusercontent.com/p/AF1QipNYK5k0jc1KVKoxx1MQ9c0doch3D-rNoRpjMPzW=w1024-h960-p-k-no  https://lh5.googleusercontent.com/p/AF1QipMBp7CcZZgSlVCi8FW1bxJd2aO7cKFImXLMGDzt=w1024-h960-p-k-no  Elevated international dishes & drinks presented in a polished destination with an elegant interior.          $$$                 NaN                           https://plus.codes/76Q9+8Q Al Khobar Saudi Arabia                           76Q9+8Q Al Khobar Saudi Arabia  No-contact delivery                  Monday 7 AM–12 AM  2025-03-31                  Tuesday 7 AM–12 AM  2025-04-01                  Wednesday 7 AM–12 AM  2025-04-02                  Thursday 7 AM–12 AM  2025-04-03                   Friday 7 AM–12 AM  2025-04-04                  Saturday 7 AM–12 AM  2025-04-05                     Sunday 7 AM–12 AM  2025-04-06                                                                                                           0% busy at 6 AM;17% busy at 7 AM;22% busy at 8 AM;25% busy at 9 AM;26% busy at 10 AM;29% busy at 11 AM;30% busy at 12 PM;31% busy at 1 PM;31% busy at 2 PM;35% busy at 3 PM;42% busy at 4 PM;47% busy at 5 PM;58% busy at 6 PM;63% busy at 7 PM;65% busy at 8 PM;55% busy at 9 PM;43% busy at 10 PM;33% busy at 11 PM;                                                                                                           0% busy at 6 AM;15% busy at 7 AM;18% busy at 8 AM;26% busy at 9 AM;33% busy at 10 AM;38% busy at 11 AM;36% busy at 12 PM;34% busy at 1 PM;33% busy at 2 PM;37% busy at 3 PM;46% busy at 4 PM;56% busy at 5 PM;62% busy at 6 PM;63% busy at 7 PM;63% busy at 8 PM;59% busy at 9 PM;51% busy at 10 PM;39% busy at 11 PM;                                                                                                                                                                                                           0% busy at 6 AM;23% busy at 7 AM;25% busy at 8 AM;29% busy at 9 AM;33% busy at 10 AM;33% busy at 11 AM;31% busy at 12 PM;28% busy at 1 PM;29% busy at 2 PM;37% busy at 3 PM;46% busy at 4 PM;54% busy at 5 PM;61% busy at 6 PM;64% busy at 7 PM;63% busy at 8 PM;59% busy at 9 PM;50% busy at 10 PM;36% busy at 11 PM;                                                                                                           0% busy at 6 AM;17% busy at 7 AM;21% busy at 8 AM;25% busy at 9 AM;32% busy at 10 AM;37% busy at 11 AM;40% busy at 12 PM;38% busy at 1 PM;36% busy at 2 PM;38% busy at 3 PM;45% busy at 4 PM;53% busy at 5 PM;62% busy at 6 PM;69% busy at 7 PM;75% busy at 8 PM;81% busy at 9 PM;79% busy at 10 PM;72% busy at 11 PM;                                                                                                          0% busy at 6 AM;26% busy at 7 AM;35% busy at 8 AM;39% busy at 9 AM;40% busy at 10 AM;44% busy at 11 AM;49% busy at 12 PM;56% busy at 1 PM;59% busy at 2 PM;65% busy at 3 PM;74% busy at 4 PM;87% busy at 5 PM;99% busy at 6 PM;100% busy at 7 PM;98% busy at 8 PM;90% busy at 9 PM;79% busy at 10 PM;65% busy at 11 PM;                                                                                                           0% busy at 6 AM;18% busy at 7 AM;30% busy at 8 AM;43% busy at 9 AM;51% busy at 10 AM;59% busy at 11 AM;60% busy at 12 PM;62% busy at 1 PM;59% busy at 2 PM;62% busy at 3 PM;68% busy at 4 PM;77% busy at 5 PM;88% busy at 6 PM;93% busy at 7 PM;92% busy at 8 PM;81% busy at 9 PM;63% busy at 10 PM;44% busy at 11 PM;                                                                                                           0% busy at 6 AM;17% busy at 7 AM;23% busy at 8 AM;28% busy at 9 AM;32% busy at 10 AM;36% busy at 11 AM;39% busy at 12 PM;37% busy at 1 PM;37% busy at 2 PM;41% busy at 3 PM;47% busy at 4 PM;56% busy at 5 PM;66% busy at 6 PM;70% busy at 7 PM;68% busy at 8 PM;62% busy at 9 PM;47% busy at 10 PM;33% busy at 11 PM;
1    Restaurant                                                                    Chettinad Restaurant         482.0     4.1                                       7922 الامير ناصر بن عبد العزيز, حي العدامة, EDJD4573، 4573, Dammam 32242, Saudi Arabia      SA      Dammam    NaN                                                                                                                                                                      NaN            +966 59 108 8097                                                                                                                Monday 7 AM–11:30 PM  2025-03-31\r\nTuesday 7 AM–11:30 PM  2025-04-01\r\nWednesday 7 AM–11:30 PM  2025-04-02\r\nThursday 7 AM–11:30 PM  2025-04-03\r\nFriday 7 AM–11:30 PM  2025-04-04\r\nSaturday 7 AM–11:30 PM  2025-04-05\r\nSunday 7 AM–11:30 PM  2025-04-06\r\n                                                                  https://www.google.com/maps/place/Chettinad+Restaurant/data=!4m5!3m4!1s0x3e49fb12c08a1287:0x38be45309d63ef75!8m2!3d26.4366424!4d50.1074179?authuser=0&hl=en&rclk=1  0x3e49fb12c08a1287:0x38be45309d63ef75  ChIJhxKKwBL7ST4Rde9jnTBFvjg                        NaN  26.436642  50.107418    South Indian restaurant                                                                                                                                                            https://lh5.googleusercontent.com/p/AF1QipNftX86soA8IaOPn42lnXHZWYYlTX42TSv2zNP3=w408-h306-k-no                        https://lh5.googleusercontent.com/p/AF1QipOEp4QmqyrV5tuZ4KyLpzb_Gss1pgDfOiHHYv0U=w1024-h960-p-k-no                        https://lh5.googleusercontent.com/p/AF1QipNWELLp1pSdws5YOuLhMzZQdhDtdClsclPjN6Eu=w1024-h960-p-k-no  https://lh5.googleusercontent.com/p/AF1QipOx8Qggo4MjKhE0-rL7ds8nixzFJ_jhRzVoLV1S=w1024-h960-p-k-no                                                                                                   NaN     SAR 1–20                 NaN                              https://plus.codes/C4P4+MX Dammam Saudi Arabia                              C4P4+MX Dammam Saudi Arabia             Delivery               Monday 7 AM–11:30 PM  2025-03-31               Tuesday 7 AM–11:30 PM  2025-04-01               Wednesday 7 AM–11:30 PM  2025-04-02               Thursday 7 AM–11:30 PM  2025-04-03                Friday 7 AM–11:30 PM  2025-04-04               Saturday 7 AM–11:30 PM  2025-04-05                  Sunday 7 AM–11:30 PM  2025-04-06                                                                                                           0% busy at 6 AM;27% busy at 7 AM;31% busy at 8 AM;32% busy at 9 AM;26% busy at 10 AM;26% busy at 11 AM;29% busy at 12 PM;31% busy at 1 PM;26% busy at 2 PM;22% busy at 3 PM;22% busy at 4 PM;34% busy at 5 PM;48% busy at 6 PM;65% busy at 7 PM;72% busy at 8 PM;65% busy at 9 PM;50% busy at 10 PM;31% busy at 11 PM;                                                                                                           0% busy at 6 AM;22% busy at 7 AM;24% busy at 8 AM;25% busy at 9 AM;25% busy at 10 AM;31% busy at 11 AM;35% busy at 12 PM;34% busy at 1 PM;29% busy at 2 PM;25% busy at 3 PM;27% busy at 4 PM;39% busy at 5 PM;54% busy at 6 PM;68% busy at 7 PM;69% busy at 8 PM;62% busy at 9 PM;46% busy at 10 PM;32% busy at 11 PM;                                                                                                                                                                                                           0% busy at 6 AM;30% busy at 7 AM;29% busy at 8 AM;28% busy at 9 AM;31% busy at 10 AM;39% busy at 11 AM;46% busy at 12 PM;43% busy at 1 PM;32% busy at 2 PM;19% busy at 3 PM;18% busy at 4 PM;32% busy at 5 PM;46% busy at 6 PM;63% busy at 7 PM;72% busy at 8 PM;62% busy at 9 PM;46% busy at 10 PM;27% busy at 11 PM;                                                                                                          0% busy at 6 AM;27% busy at 7 AM;30% busy at 8 AM;25% busy at 9 AM;23% busy at 10 AM;25% busy at 11 AM;35% busy at 12 PM;43% busy at 1 PM;37% busy at 2 PM;26% busy at 3 PM;21% busy at 4 PM;26% busy at 5 PM;48% busy at 6 PM;75% busy at 7 PM;100% busy at 8 PM;97% busy at 9 PM;78% busy at 10 PM;48% busy at 11 PM;                                                                                                           0% busy at 6 AM;27% busy at 7 AM;36% busy at 8 AM;43% busy at 9 AM;43% busy at 10 AM;52% busy at 11 AM;63% busy at 12 PM;62% busy at 1 PM;46% busy at 2 PM;26% busy at 3 PM;19% busy at 4 PM;22% busy at 5 PM;41% busy at 6 PM;62% busy at 7 PM;83% busy at 8 PM;84% busy at 9 PM;71% busy at 10 PM;45% busy at 11 PM;                                                                                                           0% busy at 6 AM;34% busy at 7 AM;41% busy at 8 AM;44% busy at 9 AM;37% busy at 10 AM;34% busy at 11 AM;39% busy at 12 PM;46% busy at 1 PM;44% busy at 2 PM;34% busy at 3 PM;31% busy at 4 PM;34% busy at 5 PM;45% busy at 6 PM;60% busy at 7 PM;73% busy at 8 PM;73% busy at 9 PM;56% busy at 10 PM;37% busy at 11 PM;                                                                                                           0% busy at 6 AM;28% busy at 7 AM;34% busy at 8 AM;36% busy at 9 AM;36% busy at 10 AM;40% busy at 11 AM;41% busy at 12 PM;39% busy at 1 PM;31% busy at 2 PM;26% busy at 3 PM;22% busy at 4 PM;31% busy at 5 PM;43% busy at 6 PM;58% busy at 7 PM;62% busy at 8 PM;54% busy at 9 PM;39% busy at 10 PM;24% busy at 11 PM;

In [74]:
print(df.isnull().sum())

keyword                      0
Title                        0
Review_Count                29
Rating                      29
Address                      0
Country                      0
City                         0
State                      617
Website                    461
Phone                      157
Open_Time                    0
Page_URL                     0
Google_id                    0
Place_id                     0
Additional_info            603
Latitude                     0
Longitude                    0
Category                     0
Main_image                  39
Image_1                     41
Image_2                     62
Image_3                    120
Description                605
Price_Range                241
Current_Status             594
Plus_code_URL              153
Plus_code                  153
Delivery                    48
Open_Time_Monday           162
Open_Time_Tuesday          162
Open_Time_Wednesday        162
Open_Time_Thursday         162
Open_Time_Friday           162
Open_Time_Saturday         162
Open_Time_Sunday           162
Popular_times_Monday       238
Popular_times_Tuesday      238
Popular_times_Wednesday    238
Popular_times_Thursday     238
Popular_times_Friday       238
Popular_times_Saturday     238
Popular_times_Sunday       238
dtype: int64

In [75]:
#df=df.drop("Place_id",axis=1)
df=df.drop("Plus_code_URL",axis=1)

#drop rows with missing target variable (Review_Count)
df = df.dropna(subset=['Review_Count'])

In [76]:
#verify
print(df.isnull().sum())

keyword                      0
Title                        0
Review_Count                 0
Rating                       0
Address                      0
Country                      0
City                         0
State                      588
Website                    433
Phone                      136
Open_Time                    0
Page_URL                     0
Google_id                    0
Place_id                     0
Additional_info            574
Latitude                     0
Longitude                    0
Category                     0
Main_image                  25
Image_1                     26
Image_2                     44
Image_3                     96
Description                576
Price_Range                212
Current_Status             565
Plus_code                  141
Delivery                    43
Open_Time_Monday           140
Open_Time_Tuesday          140
Open_Time_Wednesday        140
Open_Time_Thursday         140
Open_Time_Friday           140
Open_Time_Saturday         140
Open_Time_Sunday           140
Popular_times_Monday       210
Popular_times_Tuesday      210
Popular_times_Wednesday    210
Popular_times_Thursday     210
Popular_times_Friday       210
Popular_times_Saturday     210
Popular_times_Sunday       210
dtype: int64

In [77]:
import pandas as pd
from fuzzywuzzy import fuzz
from geopy.distance import geodesic
from itertools import combinations



# Function to calculate Haversine Distance (geo distance between two locations)
def is_nearby(lat1, lon1, lat2, lon2, threshold=0.5):
    """Returns True if two locations are within 'threshold' km."""
    return geodesic((lat1, lon1), (lat2, lon2)).km <= threshold

# Function for fuzzy name matching
def is_similar(name1, name2, threshold=85):
    """Returns True if two names are at least 'threshold'% similar."""
    return fuzz.token_sort_ratio(name1, name2) >= threshold

# Identify possible duplicate restaurants
duplicates = []

for (i, row1), (j, row2) in combinations(df.iterrows(), 2):
    if is_similar(row1["Title"], row2["Title"]) and is_nearby(row1["Latitude"], row1["Longitude"], row2["Latitude"], row2["Longitude"]):
        duplicates.append({
            "Duplicate_1_Index": i,
            "Duplicate_2_Index": j,
            "Duplicate_1_ID": row1["Place_id"],
            "Duplicate_2_ID": row2["Place_id"],
            "Name_1": row1["Title"],
            "Name_2": row2["Title"],
            "Latitude_1": row1["Latitude"],
            "Longitude_1": row1["Longitude"],
            "Latitude_2": row2["Latitude"],
            "Longitude_2": row2["Longitude"]
        })

# Create a DataFrame of duplicate pairs
duplicates_df = pd.DataFrame(duplicates)

# Print detected duplicates
print(f"Found {len(duplicates_df)} potential duplicate restaurants.")
print(duplicates_df.head())

Found 4 potential duplicate restaurants.
   Duplicate_1_Index  Duplicate_2_Index               Duplicate_1_ID  \
0                 89                100  ChIJARzcqMv9ST4RgWfun6iflek
1                291                530  ChIJYS_PR-rpST4RvXsBrnx_lGM
2                309                670  ChIJz652tDrDST4RaBstEpCvJP4
3                314                393  ChIJuRLBORkfNj4RGYIwDxMeYHE

                Duplicate_2_ID                    Name_1  \
0  ChIJX9NsoHf8ST4R5BJs3v2H5Yc  New Hyderabad Restaurant
1  ChIJTWPJx9DpST4RaOCVEfY1YVA         Nirala Restaurant
2  ChIJayEVagDpST4R7xYKjWIOyHA         Hassan Restaurant
3  ChIJ1_wQLgAfNj4R9lahI_yTgMQ       Iconic restaurant 1

                 Name_2  Latitude_1  Longitude_1  Latitude_2  Longitude_2
0  Hyderabad Restaurant   26.446150    50.097986   26.444328    50.098418
1      Rawan Restaurant   26.294145    50.210890   26.290584    50.212621
2      Asian Restaurant   26.271381    50.211313   26.274903    50.212570
3   Iconic Restaurant 3   26.238334    49.971849   26.236172    49.969727

In [78]:
display(duplicates_df)

,Duplicate_1_Index,Duplicate_2_Index,Duplicate_1_ID,Duplicate_2_ID,Name_1,Name_2,Latitude_1,Longitude_1,Latitude_2,Longitude_2
0,89,100,ChIJARzcqMv9ST4RgWfun6iflek,ChIJX9NsoHf8ST4R5BJs3v2H5Yc,New Hyderabad Restaurant,Hyderabad Restaurant,26.446150,50.097986,26.444328,50.098418
1,291,530,ChIJYS_PR-rpST4RvXsBrnx_lGM,ChIJTWPJx9DpST4RaOCVEfY1YVA,Nirala Restaurant,Rawan Restaurant,26.294145,50.210890,26.290584,50.212621
2,309,670,ChIJz652tDrDST4RaBstEpCvJP4,ChIJayEVagDpST4R7xYKjWIOyHA,Hassan Restaurant,Asian Restaurant,26.271381,50.211313,26.274903,50.212570
3,314,393,ChIJuRLBORkfNj4RGYIwDxMeYHE,ChIJ1_wQLgAfNj4R9lahI_yTgMQ,Iconic restaurant 1,Iconic Restaurant 3,26.238334,49.971849,26.236172,49.969727

In [79]:
filtered_rows = df[df["Place_id"].isin(['ChIJARzcqMv9ST4RgWfun6iflek','ChIJX9NsoHf8ST4R5BJs3v2H5Yc', 'ChIJD3HfaAD9ST4Rl8chutao5MI','ChIJm1auTwD9ST4R_Ze5Njd6qVs', 'ChIJjzaUe4L9ST4RPktViHaZS94', 'ChIJ3zqWg5T9ST4R0MmN3aS3o4E', 'ChIJTWPJx9DpST4RaOCVEfY1YVA', 'ChIJayEVagDpST4R7xYKjWIOyHA','ChIJ1_wQLgAfNj4R9lahI_yTgMQ','ChIJYS_PR-rpST4RvXsBrnx_lGM','ChIJz652tDrDST4RaBstEpCvJP4','ChIJuRLBORkfNj4RGYIwDxMeYHE'])]
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)        # No line width limit
filtered_rows

,keyword,Title,Review_Count,Rating,Address,Country,City,State,Website,Phone,Open_Time,Page_URL,Google_id,Place_id,Additional_info,Latitude,Longitude,Category,Main_image,Image_1,Image_2,Image_3,Description,Price_Range,Current_Status,Plus_code,Delivery,Open_Time_Monday,Open_Time_Tuesday,Open_Time_Wednesday,Open_Time_Thursday,Open_Time_Friday,Open_Time_Saturday,Open_Time_Sunday,Popular_times_Monday,Popular_times_Tuesday,Popular_times_Wednesday,Popular_times_Thursday,Popular_times_Friday,Popular_times_Saturday,Popular_times_Sunday
89,Restaurant,New Hyderabad Restaurant,31.0,3.9,"Al Dawasir, Unnamed Road, Dammam 32416, Saudi ...",SA,Dammam,NaN,NaN,NaN,,https://www.google.com/maps/place/New+Hyderaba...,0x3e49fdcba8dc1c01:0xe9959fa89fee6781,ChIJARzcqMv9ST4RgWfun6iflek,NaN,26.446150,50.097986,restaurants,https://lh5.googleusercontent.com/p/AF1QipPZ2S...,https://lh5.googleusercontent.com/p/AF1QipPZ2S...,https://lh5.googleusercontent.com/p/AF1QipNT3K...,NaN,NaN,NaN,NaN,C3WX+F5 Dammam Saudi Arabia,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Restaurant,Hyderabad Restaurant,42.0,4.1,"2191 ابو منصور الازهري, Al Dawasir, Dammam 324...",SA,Dammam,NaN,NaN,NaN,Monday 4 PM–3:15 AM 2025-03-31\r\nTuesday 4 P...,https://www.google.com/maps/place/Hyderabad+Re...,0x3e49fc77a06cd35f:0x87e587fdde6c12e4,ChIJX9NsoHf8ST4R5BJs3v2H5Yc,NaN,26.444328,50.098418,restaurants,https://lh5.googleusercontent.com/p/AF1QipMEWt...,https://lh5.googleusercontent.com/p/AF1QipOfSl...,https://lh5.googleusercontent.com/p/AF1QipOp3x...,https://lh5.googleusercontent.com/p/AF1QipOK-7...,NaN,SAR 1–20,NaN,C3VX+P9 Dammam Saudi Arabia,Delivery,Monday 4 PM–3:15 AM 2025-03-31,Tuesday 4 PM–3:15 AM 2025-04-01,Wednesday 4 PM–3:15 AM 2025-04-02,Thursday 4 PM–3:15 AM 2025-04-03,Friday 4 PM–3:15 AM 2025-04-04,Saturday 4 PM–3:15 AM 2025-04-05,Sunday 4 PM–3:15 AM 2025-04-06,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...,0% busy at 6 AM;0% busy at 7 AM;0% busy at 8 A...
119,Restaurant,Tawa restaurant,2.0,3.5,"C3VW+7CX, An Nakhil, Dammam 32244, Saudi Arabia",SA,Dammam,NaN,NaN,+966 53 496 7639,Monday 2 AM–11:30 PM 2025-03-31\r\nTuesday 2 ...,https://www.google.com/maps/place/Tawa+restaur...,0x3e49fd0068df710f:0xc2e4a8d6ba21c797,ChIJD3HfaAD9ST4Rl8chutao5MI,NaN,26.443245,50.096101,restaurants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delivery,Monday 2 AM–11:30 PM 2025-03-31,Tuesday 2 AM–11:30 PM 2025-04-01,Wednesday 2 AM–11:30 PM 2025-04-02,Thursday 2 AM–11:30 PM 2025-04-03,Friday 2 AM–11:30 PM 2025-04-04,Saturday 2 AM–11:30 PM 2025-04-05,Sunday 2 AM–11:30 PM 2025-04-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,Restaurant,MADINA RESTAURANT ALI ASIRI,5.0,4.0,"16th Street, Al Souq, Dammam 32242, Saudi Arabia",SA,Dammam,NaN,NaN,NaN,Monday 6 AM–11:30 PM 2025-03-31\r\nTuesday 6 ...,https://www.google.com/maps/place/MADINA+RESTA...,0x3e49fd827b94368f:0xde4b997688554b3e,ChIJjzaUe4L9ST4RPktViHaZS94,NaN,26.441496,50.099077,restaurants,https://lh5.googleusercontent.com/p/AF1QipMz8r...,https://lh5.googleusercontent.com/p/AF1QipMz8r...,https://lh5.googleusercontent.com/p/AF1QipMmYx...,https://lh5.googleusercontent.com/p/AF1QipMz8r...,NaN,NaN,NaN,C3RX+HJ Dammam Saudi Arabia,No-contact delivery,Monday 6 AM–11:30 PM 2025-03-31,Tuesday 6 AM–11:30 PM 2025-04-01,Wednesday 6 AM–11:30 PM 2025-04-02,Thursday 6 AM–11:30 PM 2025-04-03,Friday 6 AM–11:30 PM 2025-04-04,Saturday 6 AM–11:30 PM 2025-04-05,Sunday 6 AM–11:30 PM 2025-04-06,0% busy at 5 AM;35% busy at 6 AM;28% busy at 7...,0% busy at 5 AM;50% busy at 6 AM;28% busy at 7...,0% busy at 5 AM;71% busy at 6 AM;78% busy at 7...,0% busy at 5 AM;42% busy at 6 AM;35% busy at 7...,0% busy at 5 AM;0% busy at 6 AM;7% busy at 7 A...,0% busy at 5 AM;21% busy at 6 AM;7% busy at 7 ...,0% busy at 5 AM;64% busy at 6 AM;78% busy at 7...
291,Restaurant,Nirala Restaurant,230.0,4.3,"Prince Nayef St, Al Khobar Al Shamalia, 17th S...",SA,Al Khobar,NaN,NaN,+966 59 927 0079,,https://www.google.com/maps/place/Nirala+Resta...,0x3e49e9ea47cf2f61:0x63947f7cae017bbd,ChIJYS_PR-rpST4RvXsBrnx_lGM,NaN,26.294145,50.210890,restaurants,https://lh5.googleusercontent.com/p/AF1QipMCW9...,https://lh5.googleusercontent.com/p/AF1QipMVGm...,https://lh5.googleusercontent.com/p/CIABIhAA3i...,https://lh5.googleusercontent.com/p/AF1QipP9AV...,NaN,NaN,NaN,76V6+M9 Al Khobar Saudi Arabia,Drive-through,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0% busy at 4 AM;12% busy at 5 AM;25% busy at 6...,0% busy at 4 AM;18% busy at 5 AM;32% busy at 6...,0% busy at 4 AM;19% busy at 5 AM;35% busy at 6...,0% busy at 4 AM;20% busy at 5 AM;39% busy at 6...,0% busy at 4 AM;16% busy at 5 AM;30% busy at 6...,0% busy at 4 AM;14% busy at 5 AM;31% busy at 6...,0% busy at 4 AM;18% busy at 5 AM;35% busy at 6...
309,Restaurant,Hassan Restaurant,56.0,4.2,"5570 الشارع الخامس والعشرين، 7397, Al Khobar A...",SA,Al Khobar,NaN,NaN,NaN,Monday 6 AM–11 PM 2025-03-31\r\nTuesday 6 AM–...,https://www.google.com/maps/place/Hassan+Resta...,0x3e49c33ab476aecf:0xfe24af90122d1b68,ChIJz652tDrDST4RaBstEpCvJP4,NaN,26.271381,50.211313,restaurants,https://lh5.googleusercontent.com/p/AF1QipPWTv...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,NaN,NaN,76C6+HG Al Khobar Saudi Arabia,Dine-in,Monday 6 AM–11 PM 2025-03-31,Tuesday 6 AM–11 PM 2025-04-01,Wednesday 6 AM–11 PM 2025-04-02,Thursday 6 AM–11 PM 2025-04-03,Friday 6–9:30 AM 12:15–11 PM 2025-04-04,Saturday 6 AM–11 PM 2025-04-05,Sunday 6 AM–11 PM 2025-04-06,0% busy at 5 AM;82% busy at 6 AM;100% busy at ...,0% busy at 5 AM;62% busy at 6 AM;77% busy at 7...,0% busy at 5 AM;51% busy at 6 AM;70% busy at 7...,0% busy at 5 AM;67% busy at 6 AM;76% busy at 7...,0% busy at 5 AM;39% busy at 6 AM;54% busy at 7...,0% busy at 5 AM;43% busy at 6 AM;62% busy at 7...,0% busy at 5 AM;70% busy at 6 AM;87% busy at 7...
314,Restaurant,Iconic restaurant 1,14.0,3.8,"2455, Dammam 2nd Industrial City, 7913, Dammam...",SA,Dammam,NaN,http://iconichome.xyz/,+966 54 412 0072,Monday 4 AM–10 PM 2025-03-31\r\nTuesday 4 AM–...,https://www.google.com/maps/place/Iconic+resta...,0x3e361f1939c112b9:0x71601e130f308219,ChIJuRLBORkfNj4RGYIwDxMeYHE,NaN,26.238334,49.971849,restaurants,https://lh5.googleusercontent.com/p/AF1QipPYHt...,https://lh5.googleusercontent.com/p/AF1QipPYHt...,https://lh5.googleusercontent.com/p/AF1QipN0Dw...,https://lh5.googleusercontent.com/p/AF1QipPOvg...,NaN,SAR 1–20,NaN,6XQC+8P Dammam Saudi Arabia,Delivery,Monday 4 AM–10 PM 2025-03-31,Tuesday 4 AM–10 PM 2025-04-01,Wednesday 4 AM–10 PM 2025-04-02,Thursday 4 AM–10 PM 2025-04-03,Friday 4 AM–10 PM 2025-04-04,Saturday 4 AM–10 PM 2025-04-05,Sunday 4 AM–10 PM 2025-04-06,0% busy at 3 AM;40% busy at 4 AM;68% busy at 5...,0% busy at 3 AM;44% busy at 4 AM;36% busy at 5...,0% busy at 3 AM;44% busy at 4 AM;44% busy at 5...,0% busy at 3 AM;36% busy at 4 AM;64% busy at 5...,0% busy at 3 AM;20% busy at 4 AM;44% busy at 5...,0% busy at 3 AM;68% busy at 4 AM;72% busy at 5...,0% busy at 3 AM;72% busy at 4 AM;96% busy at 5...
393,Restaurant,Iconic Restaurant 3,9.0,4.2,"EIGA2205, 7650 الدمام 475, 2205, Dammam 34334,...",SA,Dammam,NaN,http://iconichome.xyz/,+966 54 607 5600,,https://www.google.com/maps/place/Iconic+Resta...,0x3e361f002e10fcd7:0xc48093fc23a156f6,ChIJ1_wQLgAfNj4R9lahI_yTgMQ,NaN,26.236172,49.969727,restaurants,https://lh5.googleusercontent.com/p/AF1QipNRV5...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 1–20,NaN,6XP9+FV Dammam Saudi Arabia,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
530,Restaurant,Rawan Restaurant,135.0,4.1,"76R7+62Q, 12th Street, Al Khobar Al Shamalia, ...",SA,Al Khobar,NaN,NaN,NaN,Monday 6:45 AM–12 PM 3:45 PM–12 AM 2025-03-31\...,https://www.google.com/maps/place/Rawan+Restau...,0x3e49e9d0c7c9634d:0x506135f61195e068,ChIJTWPJx9DpST4RaOCVEfY1YVA,NaN,26.290584,50.212621,restaurants,https://lh5.googleusercontent.com/p/AF1QipPZea...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,https://lh5.googleusercontent.com/p/CIHM0ogKEI...,NaN,SAR 1–20,NaN,NaN,Dine-in,Monday 6:45 AM–12 PM 3:45 PM–12 AM 2025-03-31,Tuesday 6:45 AM–1 PM 3:45 PM–12 AM 2025-04-01,Wednesday 6:45 AM–1 PM 3:45 PM–12 AM 2025-04-02,Thursday 6:45 AM–1 PM 3:45 PM–12 AM 2025-04-03,Friday 6:45–11 AM 3:45 PM–12 AM 2025-04-04,Saturday 6:45 AM–1 PM 3:45 PM–12 AM 2025-04-05,Sunday 6:45 AM–1 PM 3:45 PM–12 AM 2025-04-06,0% busy at 5 AM;48% busy at 6 AM;59% busy at 7...,0% busy at 5 AM;51% busy at 6 AM;62% busy at 7...,0% busy at 5 AM;56% busy at 6 AM;72% busy at 7...,0% busy at 5 AM;43% busy at 6 AM;64% busy at 7...,0% busy at 5 AM;35% busy at 6 AM;62% busy at 7...,0% busy at 5 AM;40% busy at 6 AM;51% busy at 7...,0% busy at 5 AM;67% busy at 6 AM;89% busy at 7...
670,Restaurant,Asian Restaurant,1.0,3.0,"حي الخبر الجنوبية, EEAA8642، 8642 عين دار، 243...",SA,Al Khobar,NaN,NaN,NaN,,https://www.google.com/maps/place/Asian+Restau...,0x3e49e9006a15216b:0x70c80e628d0a16ef,ChIJayEVagDpST4R7xYKjWIOyHA,NaN,26.274903,50.212570,restaurants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76F7+X2 Al Khobar Saudi Arabia,Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df[~df["Place_id"].isin(['ChIJARzcqMv9ST4RgWfun6iflek','ChIJm1auTwD9ST4R_Ze5Njd6qVs', 'ChIJ3zqWg5T9ST4R0MmN3aS3o4E', 'ChIJ1_wQLgAfNj4R9lahI_yTgMQ'])]

In [81]:
df.to_csv("cleaned_Octoparse_restaurants.csv", index=False)